package com.my.iengineer1;

import android.animation.*;
import android.app.*;
import android.content.*;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.net.*;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.widget.*;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.DialogFragment;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import org.json.*;

public class EipDPlainconcreteActivity extends AppCompatActivity {
	
	private TextView textview519;
	private ScrollView dynamic_out_vscrolllinear1;
	private LinearLayout dynamic_out_linear2;
	private LinearLayout linear394;
	private TextView textview785;
	private TextView textview790;
	private LinearLayout dynamic_out_linear3;
	private LinearLayout dynamic_out_linear7;
	private HorizontalScrollView hscroll98;
	private LinearLayout dynamic_out_linear8;
	private HorizontalScrollView hscroll22;
	private TextView textview807;
	private TextView textview1081;
	private Button dynamic_check_for_survaying;
	private TextView textview80;
	private LinearLayout dynamic_out_linear9;
	private TextView textview504;
	private Button dynamic_check_for_dimenions;
	private LinearLayout dynamic_out_linear21;
	private LinearLayout dynamic_element_remove_linear;
	private TextView textview18;
	private EditText dynamic_element_serial_numbers;
	private TextView dynamic_element_symble;
	private TextView textview1080;
	private EditText dynamic_element_serial_number;
	private TextView dynamic_element_type;
	private LinearLayout dynamic_out_linear6;
	private TextView textview791;
	private LinearLayout dynamic_out_linear5;
	private TextView textview787;
	private LinearLayout dynamic_out_linear4;
	private TextView dynamic_design_height_of_element_name;
	private EditText dynamic_design_height_of_element;
	private TextView dynamic_design_width_of_element_name;
	private EditText dynamic_design_width_of_element;
	private TextView dynamic_design_length_of_element_name;
	private EditText dynamic_design_length_of_element;
	private TextView textview1077;
	private EditText dynamic_thickness_of_wood;
	private TextView textview794;
	private TextView dynamic_thickness_of_wood_name;
	private EditText dynamic_level_of_replacement;
	private TextView textview6;
	private TextView dynamic_level_of_replacement_name;
	private TextView textview809;
	private TextView textview810;
	private TextView textview469;
	private HorizontalScrollView hscroll24;
	private LinearLayout dynamic_out_linear10;
	private HorizontalScrollView hscroll26;
	private TextView textview493;
	private HorizontalScrollView hscroll28;
	private LinearLayout dynamic_out_linear11;
	private LinearLayout linear129;
	private LinearLayout linear388;
	private LinearLayout dynamic_out_linear12;
	private HorizontalScrollView hscroll27;
	private TextView textview492;
	private LinearLayout dynamic_out_linear16;
	private LinearLayout dynamic_out_linear17;
	private HorizontalScrollView hscroll30;
	private TextView textview470;
	private EditText dynamic_replacement_point_reading;
	private TextView textview471;
	private TextView dynamic_replacement_point_reading_name;
	private TextView textview494;
	private EditText dynamic_formwork_point_reading;
	private TextView textview495;
	private TextView dynamic_formwork_point_reading_name;
	private Button dynamic_survaying_calculation_for_element;
	private TextView textview1073;
	private LinearLayout dynamic_out_linear14;
	private TextView textview481;
	private LinearLayout dynamic_out_linear13;
	private TextView dynamic_replacement_levels_difference_name;
	private EditText dynamic_replacement_levels_difference;
	private TextView dynamic_replacement_point_level_name;
	private EditText dynamic_replacement_point_level;
	private LinearLayout dynamic_out_linear15;
	private TextView dynamic_required_action_for_replacement;
	private TextView textview488;
	private TextView textview489;
	private EditText dynamic_design_formwork_level;
	private TextView textview797;
	private TextView dynamic_design_formwork_level_name;
	private LinearLayout dynamic_out_linear19;
	private TextView textview498;
	private LinearLayout dynamic_out_linear18;
	private TextView dynamic_formwork_levels_difference_name;
	private EditText dynamic_formwork_levels_difference;
	private TextView dynamic_actual_formwork_level_name;
	private EditText dynamic_actual_formwork_level;
	private LinearLayout dynamic_out_linear20;
	private TextView dynamic_required_action_for_formwork;
	private TextView textview502;
	private TextView textview503;
	private TextView textview505;
	private LinearLayout dynamic_out_linear22;
	private LinearLayout linear137;
	private LinearLayout linear389;
	private LinearLayout dynamic_out_linear25;
	private LinearLayout dynamic_out_linear24;
	private TextView textview510;
	private LinearLayout dynamic_out_linear23;
	private TextView dynamic_actual_width_of_element_name;
	private EditText dynamic_actual_width_of_element;
	private TextView dynamic_actual_length_of_element_name;
	private EditText dynamic_actual_length_of_element;
	private Button dynamic_dimenions_calculation_for_element;
	private TextView textview1074;
	private LinearLayout dynamic_out_linear27;
	private TextView textview521;
	private LinearLayout dynamic_out_linear26;
	private TextView dynamic_width_difference_for_element_name;
	private EditText dynamic_width_difference_for_element;
	private TextView textview806;
	private TextView textview525;
	private TextView dynamic_width_action_for_element;
	private TextView dynamic_length_difference_for_element_name;
	private EditText dynamic_length_difference_for_element;
	private TextView textview805;
	private TextView textview514;
	private TextView dynamic_length_action_for_element;
	private Button dynamic_element_remove;
	private TextView textview789;
	
	@Override
	protected void onCreate(Bundle _savedInstanceState) {
		super.onCreate(_savedInstanceState);
		setContentView(R.layout.eip_d_plainconcrete);
		initialize(_savedInstanceState);
		
		
		initializeLogic();
	}
	
	private void initialize(Bundle _savedInstanceState) {
		textview519 = findViewById(R.id.textview519);
		dynamic_out_vscrolllinear1 = findViewById(R.id.dynamic_out_vscrolllinear1);
		dynamic_out_linear2 = findViewById(R.id.dynamic_out_linear2);
		linear394 = findViewById(R.id.linear394);
		textview785 = findViewById(R.id.textview785);
		textview790 = findViewById(R.id.textview790);
		dynamic_out_linear3 = findViewById(R.id.dynamic_out_linear3);
		dynamic_out_linear7 = findViewById(R.id.dynamic_out_linear7);
		hscroll98 = findViewById(R.id.hscroll98);
		dynamic_out_linear8 = findViewById(R.id.dynamic_out_linear8);
		hscroll22 = findViewById(R.id.hscroll22);
		textview807 = findViewById(R.id.textview807);
		textview1081 = findViewById(R.id.textview1081);
		dynamic_check_for_survaying = findViewById(R.id.dynamic_check_for_survaying);
		textview80 = findViewById(R.id.textview80);
		dynamic_out_linear9 = findViewById(R.id.dynamic_out_linear9);
		textview504 = findViewById(R.id.textview504);
		dynamic_check_for_dimenions = findViewById(R.id.dynamic_check_for_dimenions);
		dynamic_out_linear21 = findViewById(R.id.dynamic_out_linear21);
		dynamic_element_remove_linear = findViewById(R.id.dynamic_element_remove_linear);
		textview18 = findViewById(R.id.textview18);
		dynamic_element_serial_numbers = findViewById(R.id.dynamic_element_serial_numbers);
		dynamic_element_symble = findViewById(R.id.dynamic_element_symble);
		textview1080 = findViewById(R.id.textview1080);
		dynamic_element_serial_number = findViewById(R.id.dynamic_element_serial_number);
		dynamic_element_type = findViewById(R.id.dynamic_element_type);
		dynamic_out_linear6 = findViewById(R.id.dynamic_out_linear6);
		textview791 = findViewById(R.id.textview791);
		dynamic_out_linear5 = findViewById(R.id.dynamic_out_linear5);
		textview787 = findViewById(R.id.textview787);
		dynamic_out_linear4 = findViewById(R.id.dynamic_out_linear4);
		dynamic_design_height_of_element_name = findViewById(R.id.dynamic_design_height_of_element_name);
		dynamic_design_height_of_element = findViewById(R.id.dynamic_design_height_of_element);
		dynamic_design_width_of_element_name = findViewById(R.id.dynamic_design_width_of_element_name);
		dynamic_design_width_of_element = findViewById(R.id.dynamic_design_width_of_element);
		dynamic_design_length_of_element_name = findViewById(R.id.dynamic_design_length_of_element_name);
		dynamic_design_length_of_element = findViewById(R.id.dynamic_design_length_of_element);
		textview1077 = findViewById(R.id.textview1077);
		dynamic_thickness_of_wood = findViewById(R.id.dynamic_thickness_of_wood);
		textview794 = findViewById(R.id.textview794);
		dynamic_thickness_of_wood_name = findViewById(R.id.dynamic_thickness_of_wood_name);
		dynamic_level_of_replacement = findViewById(R.id.dynamic_level_of_replacement);
		textview6 = findViewById(R.id.textview6);
		dynamic_level_of_replacement_name = findViewById(R.id.dynamic_level_of_replacement_name);
		textview809 = findViewById(R.id.textview809);
		textview810 = findViewById(R.id.textview810);
		textview469 = findViewById(R.id.textview469);
		hscroll24 = findViewById(R.id.hscroll24);
		dynamic_out_linear10 = findViewById(R.id.dynamic_out_linear10);
		hscroll26 = findViewById(R.id.hscroll26);
		textview493 = findViewById(R.id.textview493);
		hscroll28 = findViewById(R.id.hscroll28);
		dynamic_out_linear11 = findViewById(R.id.dynamic_out_linear11);
		linear129 = findViewById(R.id.linear129);
		linear388 = findViewById(R.id.linear388);
		dynamic_out_linear12 = findViewById(R.id.dynamic_out_linear12);
		hscroll27 = findViewById(R.id.hscroll27);
		textview492 = findViewById(R.id.textview492);
		dynamic_out_linear16 = findViewById(R.id.dynamic_out_linear16);
		dynamic_out_linear17 = findViewById(R.id.dynamic_out_linear17);
		hscroll30 = findViewById(R.id.hscroll30);
		textview470 = findViewById(R.id.textview470);
		dynamic_replacement_point_reading = findViewById(R.id.dynamic_replacement_point_reading);
		textview471 = findViewById(R.id.textview471);
		dynamic_replacement_point_reading_name = findViewById(R.id.dynamic_replacement_point_reading_name);
		textview494 = findViewById(R.id.textview494);
		dynamic_formwork_point_reading = findViewById(R.id.dynamic_formwork_point_reading);
		textview495 = findViewById(R.id.textview495);
		dynamic_formwork_point_reading_name = findViewById(R.id.dynamic_formwork_point_reading_name);
		dynamic_survaying_calculation_for_element = findViewById(R.id.dynamic_survaying_calculation_for_element);
		textview1073 = findViewById(R.id.textview1073);
		dynamic_out_linear14 = findViewById(R.id.dynamic_out_linear14);
		textview481 = findViewById(R.id.textview481);
		dynamic_out_linear13 = findViewById(R.id.dynamic_out_linear13);
		dynamic_replacement_levels_difference_name = findViewById(R.id.dynamic_replacement_levels_difference_name);
		dynamic_replacement_levels_difference = findViewById(R.id.dynamic_replacement_levels_difference);
		dynamic_replacement_point_level_name = findViewById(R.id.dynamic_replacement_point_level_name);
		dynamic_replacement_point_level = findViewById(R.id.dynamic_replacement_point_level);
		dynamic_out_linear15 = findViewById(R.id.dynamic_out_linear15);
		dynamic_required_action_for_replacement = findViewById(R.id.dynamic_required_action_for_replacement);
		textview488 = findViewById(R.id.textview488);
		textview489 = findViewById(R.id.textview489);
		dynamic_design_formwork_level = findViewById(R.id.dynamic_design_formwork_level);
		textview797 = findViewById(R.id.textview797);
		dynamic_design_formwork_level_name = findViewById(R.id.dynamic_design_formwork_level_name);
		dynamic_out_linear19 = findViewById(R.id.dynamic_out_linear19);
		textview498 = findViewById(R.id.textview498);
		dynamic_out_linear18 = findViewById(R.id.dynamic_out_linear18);
		dynamic_formwork_levels_difference_name = findViewById(R.id.dynamic_formwork_levels_difference_name);
		dynamic_formwork_levels_difference = findViewById(R.id.dynamic_formwork_levels_difference);
		dynamic_actual_formwork_level_name = findViewById(R.id.dynamic_actual_formwork_level_name);
		dynamic_actual_formwork_level = findViewById(R.id.dynamic_actual_formwork_level);
		dynamic_out_linear20 = findViewById(R.id.dynamic_out_linear20);
		dynamic_required_action_for_formwork = findViewById(R.id.dynamic_required_action_for_formwork);
		textview502 = findViewById(R.id.textview502);
		textview503 = findViewById(R.id.textview503);
		textview505 = findViewById(R.id.textview505);
		dynamic_out_linear22 = findViewById(R.id.dynamic_out_linear22);
		linear137 = findViewById(R.id.linear137);
		linear389 = findViewById(R.id.linear389);
		dynamic_out_linear25 = findViewById(R.id.dynamic_out_linear25);
		dynamic_out_linear24 = findViewById(R.id.dynamic_out_linear24);
		textview510 = findViewById(R.id.textview510);
		dynamic_out_linear23 = findViewById(R.id.dynamic_out_linear23);
		dynamic_actual_width_of_element_name = findViewById(R.id.dynamic_actual_width_of_element_name);
		dynamic_actual_width_of_element = findViewById(R.id.dynamic_actual_width_of_element);
		dynamic_actual_length_of_element_name = findViewById(R.id.dynamic_actual_length_of_element_name);
		dynamic_actual_length_of_element = findViewById(R.id.dynamic_actual_length_of_element);
		dynamic_dimenions_calculation_for_element = findViewById(R.id.dynamic_dimenions_calculation_for_element);
		textview1074 = findViewById(R.id.textview1074);
		dynamic_out_linear27 = findViewById(R.id.dynamic_out_linear27);
		textview521 = findViewById(R.id.textview521);
		dynamic_out_linear26 = findViewById(R.id.dynamic_out_linear26);
		dynamic_width_difference_for_element_name = findViewById(R.id.dynamic_width_difference_for_element_name);
		dynamic_width_difference_for_element = findViewById(R.id.dynamic_width_difference_for_element);
		textview806 = findViewById(R.id.textview806);
		textview525 = findViewById(R.id.textview525);
		dynamic_width_action_for_element = findViewById(R.id.dynamic_width_action_for_element);
		dynamic_length_difference_for_element_name = findViewById(R.id.dynamic_length_difference_for_element_name);
		dynamic_length_difference_for_element = findViewById(R.id.dynamic_length_difference_for_element);
		textview805 = findViewById(R.id.textview805);
		textview514 = findViewById(R.id.textview514);
		dynamic_length_action_for_element = findViewById(R.id.dynamic_length_action_for_element);
		dynamic_element_remove = findViewById(R.id.dynamic_element_remove);
		textview789 = findViewById(R.id.textview789);
	}
	
	private void initializeLogic() {
	}
	
}
