package com.my.iengineer1;

import android.animation.*;
import android.app.*;
import android.content.*;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.net.*;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.widget.*;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.DialogFragment;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import org.json.*;

public class EipDSurveyingWorksActivity extends AppCompatActivity {
	
	private ScrollView vscroll2;
	private LinearLayout linear2d;
	private LinearLayout linear_closed;
	private HorizontalScrollView hscroll36d;
	private LinearLayout linear555d;
	private LinearLayout linear105d;
	private HorizontalScrollView hscroll37d;
	private TextView textview106d;
	private HorizontalScrollView hscroll1;
	private LinearLayout linear214d;
	private HorizontalScrollView hscroll108d;
	private TextView textview109d;
	private LinearLayout linear107d;
	private LinearLayout linear108d;
	private HorizontalScrollView hscroll109d;
	private LinearLayout linear109d;
	private HorizontalScrollView hscroll110d;
	private LinearLayout linear110d;
	private HorizontalScrollView hscroll121d;
	private LinearLayout linear121d;
	private ImageView close1d;
	private LinearLayout linear720;
	private EditText edittext555d;
	private TextView textview555d;
	private TextView textview105d;
	private LinearLayout linear211d;
	private LinearLayout linear113d;
	private LinearLayout linear112d;
	private TextView textview2378;
	private LinearLayout linear111d;
	private TextView textview2d;
	private EditText edittext2d;
	private EditText edittext_am2d;
	private TextView textview1d;
	private EditText edittext1d;
	private EditText edittext_am1d;
	private EditText edittext3d;
	private TextView textview98;
	private TextView textview3d;
	private LinearLayout linear118d;
	private LinearLayout linear119d;
	private LinearLayout linear_dynamic_surveying_works_level;
	private Button button1d;
	private LinearLayout linear217d;
	private LinearLayout linear216d;
	private LinearLayout linear215d;
	private TextView textview217d;
	private TextView textview216d;
	private TextView textview215d;
	private ImageView close2d;
	private LinearLayout linear116d;
	private LinearLayout linear115d;
	private LinearLayout linear114d;
	private EditText edittext6d;
	private EditText edittext_am6d;
	private EditText edittext5d;
	private EditText edittext_am5d;
	private EditText edittext4d;
	private EditText edittext7d;
	private TextView textview2383;
	private TextView textview7d;
	private EditText edittext8d;
	private TextView textview2443;
	private TextView textview8d;
	private EditText edittext9d;
	private TextView textview2431;
	private TextView textview9d;
	private EditText edittext10d;
	private TextView textview2445;
	private TextView textview10d;
	private EditText edittext11d;
	private TextView textview334;
	private TextView textview11d;
	
	@Override
	protected void onCreate(Bundle _savedInstanceState) {
		super.onCreate(_savedInstanceState);
		setContentView(R.layout.eip_d_surveying_works);
		initialize(_savedInstanceState);
		
		
		initializeLogic();
	}
	
	private void initialize(Bundle _savedInstanceState) {
		vscroll2 = findViewById(R.id.vscroll2);
		linear2d = findViewById(R.id.linear2d);
		linear_closed = findViewById(R.id.linear_closed);
		hscroll36d = findViewById(R.id.hscroll36d);
		linear555d = findViewById(R.id.linear555d);
		linear105d = findViewById(R.id.linear105d);
		hscroll37d = findViewById(R.id.hscroll37d);
		textview106d = findViewById(R.id.textview106d);
		hscroll1 = findViewById(R.id.hscroll1);
		linear214d = findViewById(R.id.linear214d);
		hscroll108d = findViewById(R.id.hscroll108d);
		textview109d = findViewById(R.id.textview109d);
		linear107d = findViewById(R.id.linear107d);
		linear108d = findViewById(R.id.linear108d);
		hscroll109d = findViewById(R.id.hscroll109d);
		linear109d = findViewById(R.id.linear109d);
		hscroll110d = findViewById(R.id.hscroll110d);
		linear110d = findViewById(R.id.linear110d);
		hscroll121d = findViewById(R.id.hscroll121d);
		linear121d = findViewById(R.id.linear121d);
		close1d = findViewById(R.id.close1d);
		linear720 = findViewById(R.id.linear720);
		edittext555d = findViewById(R.id.edittext555d);
		textview555d = findViewById(R.id.textview555d);
		textview105d = findViewById(R.id.textview105d);
		linear211d = findViewById(R.id.linear211d);
		linear113d = findViewById(R.id.linear113d);
		linear112d = findViewById(R.id.linear112d);
		textview2378 = findViewById(R.id.textview2378);
		linear111d = findViewById(R.id.linear111d);
		textview2d = findViewById(R.id.textview2d);
		edittext2d = findViewById(R.id.edittext2d);
		edittext_am2d = findViewById(R.id.edittext_am2d);
		textview1d = findViewById(R.id.textview1d);
		edittext1d = findViewById(R.id.edittext1d);
		edittext_am1d = findViewById(R.id.edittext_am1d);
		edittext3d = findViewById(R.id.edittext3d);
		textview98 = findViewById(R.id.textview98);
		textview3d = findViewById(R.id.textview3d);
		linear118d = findViewById(R.id.linear118d);
		linear119d = findViewById(R.id.linear119d);
		linear_dynamic_surveying_works_level = findViewById(R.id.linear_dynamic_surveying_works_level);
		button1d = findViewById(R.id.button1d);
		linear217d = findViewById(R.id.linear217d);
		linear216d = findViewById(R.id.linear216d);
		linear215d = findViewById(R.id.linear215d);
		textview217d = findViewById(R.id.textview217d);
		textview216d = findViewById(R.id.textview216d);
		textview215d = findViewById(R.id.textview215d);
		close2d = findViewById(R.id.close2d);
		linear116d = findViewById(R.id.linear116d);
		linear115d = findViewById(R.id.linear115d);
		linear114d = findViewById(R.id.linear114d);
		edittext6d = findViewById(R.id.edittext6d);
		edittext_am6d = findViewById(R.id.edittext_am6d);
		edittext5d = findViewById(R.id.edittext5d);
		edittext_am5d = findViewById(R.id.edittext_am5d);
		edittext4d = findViewById(R.id.edittext4d);
		edittext7d = findViewById(R.id.edittext7d);
		textview2383 = findViewById(R.id.textview2383);
		textview7d = findViewById(R.id.textview7d);
		edittext8d = findViewById(R.id.edittext8d);
		textview2443 = findViewById(R.id.textview2443);
		textview8d = findViewById(R.id.textview8d);
		edittext9d = findViewById(R.id.edittext9d);
		textview2431 = findViewById(R.id.textview2431);
		textview9d = findViewById(R.id.textview9d);
		edittext10d = findViewById(R.id.edittext10d);
		textview2445 = findViewById(R.id.textview2445);
		textview10d = findViewById(R.id.textview10d);
		edittext11d = findViewById(R.id.edittext11d);
		textview334 = findViewById(R.id.textview334);
		textview11d = findViewById(R.id.textview11d);
	}
	
	private void initializeLogic() {
	}
	
}
