package com.my.iengineer1;
import android.animation.*;
import android.app.*;
import android.content.*;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.net.*;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.widget.*;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.*;
import androidx.fragment.app.Fragment;
import com.github.angads25.filepicker.*;
import com.google.android.material.button.*;
import com.google.android.material.card.*;
import com.google.android.material.chip.*;
import com.google.android.material.chip.ChipGroup;
import com.google.android.material.divider.MaterialDivider;
import com.google.android.material.textfield.*;
import com.leinardi.android.speeddial.*;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import net.cachapa.expandablelayout.*;
import net.cachapa.expandablelayout.ExpandableLayout;
import org.json.*;


public class NewFinishesFragmentActivity extends Fragment {
	
	private ScrollView scroll_view;
	private LinearLayout main_container;
	private MaterialCardView cardview7;
	private LinearLayout linear25;
	private MaterialCardView header_card;
	private MaterialDivider material_divider26;
	private ExpandableLayout expandableLayout;
	private LinearLayout header_section;
	private LinearLayout linear41;
	private TextInputLayout textinputlayout4;
	private LinearLayout linear42;
	private TextInputEditText name;
	private MaterialButton helpButton;
	private MaterialButton expand_arrow;
	private MaterialButton close;
	private LinearLayout linear43;
	private LinearLayout stepper_container;
	private MaterialCardView shape_step_card;
	private MaterialCardView dimensions_step_card;
	private MaterialCardView plastering_step_card;
	private MaterialCardView final_finish_step_card;
	private MaterialCardView openings_step_card;
	private MaterialCardView results_card;
	private LinearLayout step_1;
	private View progress_line_1;
	private LinearLayout step_2;
	private View progress_line_2;
	private LinearLayout step_3;
	private View progress_line_3;
	private LinearLayout step_4;
	private FrameLayout frame_layout4;
	private TextView step_1_label;
	private MaterialCardView step_1_indicator;
	private MaterialCardView step_1_check;
	private TextView step_1_number;
	private TextView textview4;
	private FrameLayout frame_layout5;
	private TextView step_2_label;
	private MaterialCardView step_2_indicator;
	private MaterialCardView step_2_check;
	private TextView step_2_number;
	private TextView textview5;
	private FrameLayout frame_layout6;
	private TextView step_3_label;
	private MaterialCardView step_3_indicator;
	private MaterialCardView step_3_check;
	private TextView step_3_number;
	private TextView textview6;
	private FrameLayout frame_layout7;
	private TextView step_4_label;
	private MaterialCardView step_4_indicator;
	private MaterialCardView step_4_check;
	private TextView step_4_number;
	private TextView textview7;
	private LinearLayout linear44;
	private LinearLayout linear45;
	private TextInputLayout shape_layout;
	private MaterialCardView cardview15;
	private LinearLayout linear46;
	private MaterialCardView cardview3;
	private ImageView icon_shape;
	private TextView textview63;
	private TextView textview13;
	private TextView textview64;
	private AutoCompleteTextView shape_dropdown;
	private LinearLayout linear27;
	private LinearLayout linear47;
	private MaterialCardView cardview16;
	private LinearLayout linear48;
	private ImageView icon_dimensions;
	private TextView textview66;
	private TextView textview8;
	private LinearLayout linear7;
	private LinearLayout linear8;
	private TextInputLayout plastering_type_layout;
	private MaterialCardView cardview5;
	private LinearLayout linear9;
	private ImageView imageview3;
	private TextView textview14;
	private TextView textview15;
	private AutoCompleteTextView plastering_type_dropdown;
	private LinearLayout linear10;
	private LinearLayout linear11;
	private TextView textview18;
	private ChipGroup finish_type_chip_group;
	private MaterialCardView cardview6;
	private LinearLayout linear12;
	private ImageView imageview4;
	private TextView textview16;
	private TextView textview17;
	private Chip chip_stone;
	private Chip chip_paint;
	private Chip chip_savieto;
	private LinearLayout linear_openings;
	private MaterialCardView cardview17;
	private TextView textview71;
	private TextView textview72;
	private LinearLayout mn_st_lyot;
	private ImageView icon_openings;
	private LinearLayout linear29;
	private LinearLayout linear49;
	private LinearLayout linear30;
	private MaterialCardView cardview8;
	private TextView textview9;
	private ImageView icon_results;
	private TextInputLayout textinputlayout_total;
	private TextInputLayout textinputlayout_open;
	private TextInputEditText total_area;
	private TextInputEditText total_opening;
	
	@NonNull
	@Override
	public View onCreateView(@NonNull LayoutInflater _inflater, @Nullable ViewGroup _container, @Nullable Bundle _savedInstanceState) {
		View _view = _inflater.inflate(R.layout.new_finishes_fragment, _container, false);
		initialize(_savedInstanceState, _view);
		initializeLogic();
		return _view;
	}
	
	private void initialize(Bundle _savedInstanceState, View _view) {
		scroll_view = _view.findViewById(R.id.scroll_view);
		main_container = _view.findViewById(R.id.main_container);
		cardview7 = _view.findViewById(R.id.cardview7);
		linear25 = _view.findViewById(R.id.linear25);
		header_card = _view.findViewById(R.id.header_card);
		material_divider26 = _view.findViewById(R.id.material_divider26);
		expandableLayout = _view.findViewById(R.id.expandableLayout);
		header_section = _view.findViewById(R.id.header_section);
		linear41 = _view.findViewById(R.id.linear41);
		textinputlayout4 = _view.findViewById(R.id.textinputlayout4);
		linear42 = _view.findViewById(R.id.linear42);
		name = _view.findViewById(R.id.name);
		helpButton = _view.findViewById(R.id.helpButton);
		expand_arrow = _view.findViewById(R.id.expand_arrow);
		close = _view.findViewById(R.id.close);
		linear43 = _view.findViewById(R.id.linear43);
		stepper_container = _view.findViewById(R.id.stepper_container);
		shape_step_card = _view.findViewById(R.id.shape_step_card);
		dimensions_step_card = _view.findViewById(R.id.dimensions_step_card);
		plastering_step_card = _view.findViewById(R.id.plastering_step_card);
		final_finish_step_card = _view.findViewById(R.id.final_finish_step_card);
		openings_step_card = _view.findViewById(R.id.openings_step_card);
		results_card = _view.findViewById(R.id.results_card);
		step_1 = _view.findViewById(R.id.step_1);
		progress_line_1 = _view.findViewById(R.id.progress_line_1);
		step_2 = _view.findViewById(R.id.step_2);
		progress_line_2 = _view.findViewById(R.id.progress_line_2);
		step_3 = _view.findViewById(R.id.step_3);
		progress_line_3 = _view.findViewById(R.id.progress_line_3);
		step_4 = _view.findViewById(R.id.step_4);
		frame_layout4 = _view.findViewById(R.id.frame_layout4);
		step_1_label = _view.findViewById(R.id.step_1_label);
		step_1_indicator = _view.findViewById(R.id.step_1_indicator);
		step_1_check = _view.findViewById(R.id.step_1_check);
		step_1_number = _view.findViewById(R.id.step_1_number);
		textview4 = _view.findViewById(R.id.textview4);
		frame_layout5 = _view.findViewById(R.id.frame_layout5);
		step_2_label = _view.findViewById(R.id.step_2_label);
		step_2_indicator = _view.findViewById(R.id.step_2_indicator);
		step_2_check = _view.findViewById(R.id.step_2_check);
		step_2_number = _view.findViewById(R.id.step_2_number);
		textview5 = _view.findViewById(R.id.textview5);
		frame_layout6 = _view.findViewById(R.id.frame_layout6);
		step_3_label = _view.findViewById(R.id.step_3_label);
		step_3_indicator = _view.findViewById(R.id.step_3_indicator);
		step_3_check = _view.findViewById(R.id.step_3_check);
		step_3_number = _view.findViewById(R.id.step_3_number);
		textview6 = _view.findViewById(R.id.textview6);
		frame_layout7 = _view.findViewById(R.id.frame_layout7);
		step_4_label = _view.findViewById(R.id.step_4_label);
		step_4_indicator = _view.findViewById(R.id.step_4_indicator);
		step_4_check = _view.findViewById(R.id.step_4_check);
		step_4_number = _view.findViewById(R.id.step_4_number);
		textview7 = _view.findViewById(R.id.textview7);
		linear44 = _view.findViewById(R.id.linear44);
		linear45 = _view.findViewById(R.id.linear45);
		shape_layout = _view.findViewById(R.id.shape_layout);
		cardview15 = _view.findViewById(R.id.cardview15);
		linear46 = _view.findViewById(R.id.linear46);
		cardview3 = _view.findViewById(R.id.cardview3);
		icon_shape = _view.findViewById(R.id.icon_shape);
		textview63 = _view.findViewById(R.id.textview63);
		textview13 = _view.findViewById(R.id.textview13);
		textview64 = _view.findViewById(R.id.textview64);
		shape_dropdown = _view.findViewById(R.id.shape_dropdown);
		linear27 = _view.findViewById(R.id.linear27);
		linear47 = _view.findViewById(R.id.linear47);
		cardview16 = _view.findViewById(R.id.cardview16);
		linear48 = _view.findViewById(R.id.linear48);
		icon_dimensions = _view.findViewById(R.id.icon_dimensions);
		textview66 = _view.findViewById(R.id.textview66);
		textview8 = _view.findViewById(R.id.textview8);
		linear7 = _view.findViewById(R.id.linear7);
		linear8 = _view.findViewById(R.id.linear8);
		plastering_type_layout = _view.findViewById(R.id.plastering_type_layout);
		cardview5 = _view.findViewById(R.id.cardview5);
		linear9 = _view.findViewById(R.id.linear9);
		imageview3 = _view.findViewById(R.id.imageview3);
		textview14 = _view.findViewById(R.id.textview14);
		textview15 = _view.findViewById(R.id.textview15);
		plastering_type_dropdown = _view.findViewById(R.id.plastering_type_dropdown);
		linear10 = _view.findViewById(R.id.linear10);
		linear11 = _view.findViewById(R.id.linear11);
		textview18 = _view.findViewById(R.id.textview18);
		finish_type_chip_group = _view.findViewById(R.id.finish_type_chip_group);
		cardview6 = _view.findViewById(R.id.cardview6);
		linear12 = _view.findViewById(R.id.linear12);
		imageview4 = _view.findViewById(R.id.imageview4);
		textview16 = _view.findViewById(R.id.textview16);
		textview17 = _view.findViewById(R.id.textview17);
		chip_stone = _view.findViewById(R.id.chip_stone);
		chip_paint = _view.findViewById(R.id.chip_paint);
		chip_savieto = _view.findViewById(R.id.chip_savieto);
		linear_openings = _view.findViewById(R.id.linear_openings);
		cardview17 = _view.findViewById(R.id.cardview17);
		textview71 = _view.findViewById(R.id.textview71);
		textview72 = _view.findViewById(R.id.textview72);
		mn_st_lyot = _view.findViewById(R.id.mn_st_lyot);
		icon_openings = _view.findViewById(R.id.icon_openings);
		linear29 = _view.findViewById(R.id.linear29);
		linear49 = _view.findViewById(R.id.linear49);
		linear30 = _view.findViewById(R.id.linear30);
		cardview8 = _view.findViewById(R.id.cardview8);
		textview9 = _view.findViewById(R.id.textview9);
		icon_results = _view.findViewById(R.id.icon_results);
		textinputlayout_total = _view.findViewById(R.id.textinputlayout_total);
		textinputlayout_open = _view.findViewById(R.id.textinputlayout_open);
		total_area = _view.findViewById(R.id.total_area);
		total_opening = _view.findViewById(R.id.total_opening);
	}
	
	private void initializeLogic() {
	}
	
}
