package com.my.iengineer1;
import android.animation.*;
import android.app.*;
import android.content.*;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.net.*;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.widget.*;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.*;
import androidx.fragment.app.Fragment;
import com.github.angads25.filepicker.*;
import com.leinardi.android.speeddial.*;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import net.cachapa.expandablelayout.*;
import org.json.*;


public class SandConeTestFragmentActivity extends Fragment {
	
	private LinearLayout linear1;
	private LinearLayout linear2;
	private ScrollView vscroll1;
	private LinearLayout linear3;
	private TextView textViewCalculations;
	private Button buttonToggleCalculations;
	private LinearLayout linear5;
	private LinearLayout linear4;
	private TextView textview1;
	private TextView textview4;
	private TextView textview6;
	private TextView textview2;
	private TextView textview3;
	private TextView textview5;
	private TableLayout table_layout3;
	private TableRow table_row0;
	private TableRow table_row1;
	private TableRow table_row2;
	private TableRow table_row3;
	private TableRow table_row4;
	private TableRow table_row5;
	private TableRow table_row6;
	private TableRow table_row7;
	private TableRow table_row8;
	private TableRow table_row9;
	private TableRow table_row10;
	private TableRow table_row11;
	private TableRow table_row12;
	private TableRow table_row13;
	private TableRow table_row14;
	private TableRow table_row15;
	private TableRow table_row16;
	private TableRow table_row17;
	private TableRow table_row18;
	private TableRow table_row19;
	private TableRow table_row20;
	private TableRow table_row21;
	private TableRow table_row22;
	private TextView textview7;
	private TextView textview8;
	private TextView textview9;
	private TextView textview10;
	private TextView textview11;
	private EditText editTextW1;
	private TextView textview12;
	private TextView textview13;
	private EditText editTextW2;
	private TextView textview14;
	private TextView textview15;
	private EditText editTextV1;
	private TextView textview16;
	private TextView textview17;
	private EditText DryDensity;
	private TextView textview18;
	private TextView textview19;
	private TextView textview20;
	private EditText editTextW3;
	private TextView textview21;
	private TextView w4_label;
	private EditText editTextW4;
	private TextView w4_unit;
	private TextView ws_label;
	private EditText editTextWs;
	private TextView ws_unit;
	private TextView textview27;
	private TextView textview28;
	private EditText editTextW5;
	private TextView textview29;
	private TextView textview30;
	private EditText editTextW6;
	private TextView textview31;
	private TextView textview32;
	private EditText editTextWh;
	private TextView textview33;
	private TextView v2_label;
	private EditText editTextV2;
	private TextView v2_unit;
	private TextView textview35;
	private EditText editTextW7;
	private TextView textview36;
	private TextView textview37;
	private EditText editTextW8;
	private TextView textview38;
	private TextView textview39;
	private EditText editTextW9;
	private TextView textview40;
	private TextView textview41;
	private EditText TotalSoilUnitWeight;
	private TextView textview42;
	private TextView textview43;
	private EditText fieldWaterContent;
	private TextView textview44;
	private TextView textview45;
	private EditText fieldDryUnitWeight;
	private TextView textview46;
	private TextView textview47;
	private EditText LaboratoryMaxDryUnitWeight;
	private TextView textview48;
	private TextView textview49;
	private EditText relativeDensity;
	private TextView textview50;
	
	@NonNull
	@Override
	public View onCreateView(@NonNull LayoutInflater _inflater, @Nullable ViewGroup _container, @Nullable Bundle _savedInstanceState) {
		View _view = _inflater.inflate(R.layout.sand_cone_test_fragment, _container, false);
		initialize(_savedInstanceState, _view);
		initializeLogic();
		return _view;
	}
	
	private void initialize(Bundle _savedInstanceState, View _view) {
		linear1 = _view.findViewById(R.id.linear1);
		linear2 = _view.findViewById(R.id.linear2);
		vscroll1 = _view.findViewById(R.id.vscroll1);
		linear3 = _view.findViewById(R.id.linear3);
		textViewCalculations = _view.findViewById(R.id.textViewCalculations);
		buttonToggleCalculations = _view.findViewById(R.id.buttonToggleCalculations);
		linear5 = _view.findViewById(R.id.linear5);
		linear4 = _view.findViewById(R.id.linear4);
		textview1 = _view.findViewById(R.id.textview1);
		textview4 = _view.findViewById(R.id.textview4);
		textview6 = _view.findViewById(R.id.textview6);
		textview2 = _view.findViewById(R.id.textview2);
		textview3 = _view.findViewById(R.id.textview3);
		textview5 = _view.findViewById(R.id.textview5);
		table_layout3 = _view.findViewById(R.id.table_layout3);
		table_row0 = _view.findViewById(R.id.table_row0);
		table_row1 = _view.findViewById(R.id.table_row1);
		table_row2 = _view.findViewById(R.id.table_row2);
		table_row3 = _view.findViewById(R.id.table_row3);
		table_row4 = _view.findViewById(R.id.table_row4);
		table_row5 = _view.findViewById(R.id.table_row5);
		table_row6 = _view.findViewById(R.id.table_row6);
		table_row7 = _view.findViewById(R.id.table_row7);
		table_row8 = _view.findViewById(R.id.table_row8);
		table_row9 = _view.findViewById(R.id.table_row9);
		table_row10 = _view.findViewById(R.id.table_row10);
		table_row11 = _view.findViewById(R.id.table_row11);
		table_row12 = _view.findViewById(R.id.table_row12);
		table_row13 = _view.findViewById(R.id.table_row13);
		table_row14 = _view.findViewById(R.id.table_row14);
		table_row15 = _view.findViewById(R.id.table_row15);
		table_row16 = _view.findViewById(R.id.table_row16);
		table_row17 = _view.findViewById(R.id.table_row17);
		table_row18 = _view.findViewById(R.id.table_row18);
		table_row19 = _view.findViewById(R.id.table_row19);
		table_row20 = _view.findViewById(R.id.table_row20);
		table_row21 = _view.findViewById(R.id.table_row21);
		table_row22 = _view.findViewById(R.id.table_row22);
		textview7 = _view.findViewById(R.id.textview7);
		textview8 = _view.findViewById(R.id.textview8);
		textview9 = _view.findViewById(R.id.textview9);
		textview10 = _view.findViewById(R.id.textview10);
		textview11 = _view.findViewById(R.id.textview11);
		editTextW1 = _view.findViewById(R.id.editTextW1);
		textview12 = _view.findViewById(R.id.textview12);
		textview13 = _view.findViewById(R.id.textview13);
		editTextW2 = _view.findViewById(R.id.editTextW2);
		textview14 = _view.findViewById(R.id.textview14);
		textview15 = _view.findViewById(R.id.textview15);
		editTextV1 = _view.findViewById(R.id.editTextV1);
		textview16 = _view.findViewById(R.id.textview16);
		textview17 = _view.findViewById(R.id.textview17);
		DryDensity = _view.findViewById(R.id.DryDensity);
		textview18 = _view.findViewById(R.id.textview18);
		textview19 = _view.findViewById(R.id.textview19);
		textview20 = _view.findViewById(R.id.textview20);
		editTextW3 = _view.findViewById(R.id.editTextW3);
		textview21 = _view.findViewById(R.id.textview21);
		w4_label = _view.findViewById(R.id.w4_label);
		editTextW4 = _view.findViewById(R.id.editTextW4);
		w4_unit = _view.findViewById(R.id.w4_unit);
		ws_label = _view.findViewById(R.id.ws_label);
		editTextWs = _view.findViewById(R.id.editTextWs);
		ws_unit = _view.findViewById(R.id.ws_unit);
		textview27 = _view.findViewById(R.id.textview27);
		textview28 = _view.findViewById(R.id.textview28);
		editTextW5 = _view.findViewById(R.id.editTextW5);
		textview29 = _view.findViewById(R.id.textview29);
		textview30 = _view.findViewById(R.id.textview30);
		editTextW6 = _view.findViewById(R.id.editTextW6);
		textview31 = _view.findViewById(R.id.textview31);
		textview32 = _view.findViewById(R.id.textview32);
		editTextWh = _view.findViewById(R.id.editTextWh);
		textview33 = _view.findViewById(R.id.textview33);
		v2_label = _view.findViewById(R.id.v2_label);
		editTextV2 = _view.findViewById(R.id.editTextV2);
		v2_unit = _view.findViewById(R.id.v2_unit);
		textview35 = _view.findViewById(R.id.textview35);
		editTextW7 = _view.findViewById(R.id.editTextW7);
		textview36 = _view.findViewById(R.id.textview36);
		textview37 = _view.findViewById(R.id.textview37);
		editTextW8 = _view.findViewById(R.id.editTextW8);
		textview38 = _view.findViewById(R.id.textview38);
		textview39 = _view.findViewById(R.id.textview39);
		editTextW9 = _view.findViewById(R.id.editTextW9);
		textview40 = _view.findViewById(R.id.textview40);
		textview41 = _view.findViewById(R.id.textview41);
		TotalSoilUnitWeight = _view.findViewById(R.id.TotalSoilUnitWeight);
		textview42 = _view.findViewById(R.id.textview42);
		textview43 = _view.findViewById(R.id.textview43);
		fieldWaterContent = _view.findViewById(R.id.fieldWaterContent);
		textview44 = _view.findViewById(R.id.textview44);
		textview45 = _view.findViewById(R.id.textview45);
		fieldDryUnitWeight = _view.findViewById(R.id.fieldDryUnitWeight);
		textview46 = _view.findViewById(R.id.textview46);
		textview47 = _view.findViewById(R.id.textview47);
		LaboratoryMaxDryUnitWeight = _view.findViewById(R.id.LaboratoryMaxDryUnitWeight);
		textview48 = _view.findViewById(R.id.textview48);
		textview49 = _view.findViewById(R.id.textview49);
		relativeDensity = _view.findViewById(R.id.relativeDensity);
		textview50 = _view.findViewById(R.id.textview50);
		
		buttonToggleCalculations.setOnClickListener((_view) -> {
			
		});
	}
	
	private void initializeLogic() {
	}
	
}
