package com.my.iengineer1;

import android.animation.*;
import android.app.*;
import android.content.*;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.net.*;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.widget.*;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.DialogFragment;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import org.json.*;

public class ToipDForceMainCheckDesignActivity extends AppCompatActivity {
	
	private TextView textview147d;
	private ScrollView vscroll2;
	private LinearLayout linear2d;
	private LinearLayout linear_closed;
	private HorizontalScrollView hscroll36d;
	private LinearLayout linear555d;
	private TextView textview102d;
	private TextView textview103d;
	private LinearLayout linear201d;
	private HorizontalScrollView hscroll201d;
	private LinearLayout linear202d;
	private HorizontalScrollView hscroll202d;
	private LinearLayout linear203d;
	private HorizontalScrollView hscroll203d;
	private LinearLayout linear204d;
	private HorizontalScrollView hscroll204d;
	private LinearLayout linear205d;
	private HorizontalScrollView hscroll205d;
	private LinearLayout linear206d;
	private HorizontalScrollView hscroll206d;
	private LinearLayout linear207d;
	private HorizontalScrollView hscroll207d;
	private LinearLayout linear208d;
	private HorizontalScrollView hscroll208d;
	private LinearLayout linear209d;
	private HorizontalScrollView hscroll209d;
	private Button button1d;
	private HorizontalScrollView hscroll52d;
	private TextView textview104d;
	private TextView textview2448;
	private LinearLayout linear210d;
	private HorizontalScrollView hscroll210d;
	private LinearLayout linear211d;
	private TextView textview2452;
	private LinearLayout linear221d;
	private TextView textview519;
	private TextView textview2449;
	private LinearLayout linear333d;
	private TextView textview2451;
	private TextView textview2450;
	private LinearLayout linear722;
	private ImageView closed;
	private LinearLayout linear720;
	private TextView textview180;
	private TextView textview2412;
	private EditText edittext556d;
	private TextView textview160;
	private EditText edittext555d;
	private TextView textview555d;
	private EditText edittext1d;
	private TextView textview1d;
	private EditText edittext2d;
	private TextView textview2d;
	private EditText edittext_am3d;
	private TextView textview1457;
	private EditText edittext3d;
	private TextView textview607;
	private TextView textview3d;
	private EditText edittext_am4d;
	private TextView textview1426;
	private EditText edittext4d;
	private TextView textview1427;
	private TextView textview4d;
	private EditText edittext_am5d;
	private TextView textview1428;
	private EditText edittext5d;
	private TextView textview1429;
	private TextView textview5d;
	private EditText edittext_am6d;
	private EditText edittext6d;
	private TextView textview1431;
	private TextView textview6d;
	private EditText edittext_am7d;
	private TextView textview107d;
	private EditText edittext7d;
	private TextView textview601;
	private TextView textview7d;
	private EditText edittext_am8d;
	private TextView textview108d;
	private EditText edittext8d;
	private TextView textview2429;
	private TextView textview8d;
	private EditText edittext_am9d;
	private TextView textview611;
	private EditText edittext9d;
	private TextView textview609;
	private TextView textview9d;
	private TextView textview2433;
	private EditText edittext10d;
	private TextView textview98;
	private TextView textview10d;
	private TextView textview2440;
	private EditText edittext11d;
	private TextView textview2383;
	private TextView textview11d;
	private TextView textview122d;
	private TextView textview123d;
	private LinearLayout linear222d;
	private TextView textview2434;
	private EditText edittext43d;
	private EditText edittext_am12d;
	private TextView textview2441;
	private EditText edittext12d;
	private TextView textview606;
	private TextView textview334;
	private TextView textview12d;
	private LinearLayout linear213d;
	private TextView textview133d;
	private TextView textview134d;
	private TextView textview135d;
	private TextView textview2442;
	private EditText edittext13d;
	private TextView textview2443;
	private TextView textview13d;
	private LinearLayout linear214d;
	private TextView textview144d;
	private TextView textview145d;
	private TextView textview146d;
	private TextView textview2447;
	private EditText edittext14d;
	private TextView textview2431;
	private TextView textview14d;
	
	@Override
	protected void onCreate(Bundle _savedInstanceState) {
		super.onCreate(_savedInstanceState);
		setContentView(R.layout.toip_d_force_main_check_design);
		initialize(_savedInstanceState);
		
		
		initializeLogic();
	}
	
	private void initialize(Bundle _savedInstanceState) {
		textview147d = findViewById(R.id.textview147d);
		vscroll2 = findViewById(R.id.vscroll2);
		linear2d = findViewById(R.id.linear2d);
		linear_closed = findViewById(R.id.linear_closed);
		hscroll36d = findViewById(R.id.hscroll36d);
		linear555d = findViewById(R.id.linear555d);
		textview102d = findViewById(R.id.textview102d);
		textview103d = findViewById(R.id.textview103d);
		linear201d = findViewById(R.id.linear201d);
		hscroll201d = findViewById(R.id.hscroll201d);
		linear202d = findViewById(R.id.linear202d);
		hscroll202d = findViewById(R.id.hscroll202d);
		linear203d = findViewById(R.id.linear203d);
		hscroll203d = findViewById(R.id.hscroll203d);
		linear204d = findViewById(R.id.linear204d);
		hscroll204d = findViewById(R.id.hscroll204d);
		linear205d = findViewById(R.id.linear205d);
		hscroll205d = findViewById(R.id.hscroll205d);
		linear206d = findViewById(R.id.linear206d);
		hscroll206d = findViewById(R.id.hscroll206d);
		linear207d = findViewById(R.id.linear207d);
		hscroll207d = findViewById(R.id.hscroll207d);
		linear208d = findViewById(R.id.linear208d);
		hscroll208d = findViewById(R.id.hscroll208d);
		linear209d = findViewById(R.id.linear209d);
		hscroll209d = findViewById(R.id.hscroll209d);
		button1d = findViewById(R.id.button1d);
		hscroll52d = findViewById(R.id.hscroll52d);
		textview104d = findViewById(R.id.textview104d);
		textview2448 = findViewById(R.id.textview2448);
		linear210d = findViewById(R.id.linear210d);
		hscroll210d = findViewById(R.id.hscroll210d);
		linear211d = findViewById(R.id.linear211d);
		textview2452 = findViewById(R.id.textview2452);
		linear221d = findViewById(R.id.linear221d);
		textview519 = findViewById(R.id.textview519);
		textview2449 = findViewById(R.id.textview2449);
		linear333d = findViewById(R.id.linear333d);
		textview2451 = findViewById(R.id.textview2451);
		textview2450 = findViewById(R.id.textview2450);
		linear722 = findViewById(R.id.linear722);
		closed = findViewById(R.id.closed);
		linear720 = findViewById(R.id.linear720);
		textview180 = findViewById(R.id.textview180);
		textview2412 = findViewById(R.id.textview2412);
		edittext556d = findViewById(R.id.edittext556d);
		textview160 = findViewById(R.id.textview160);
		edittext555d = findViewById(R.id.edittext555d);
		textview555d = findViewById(R.id.textview555d);
		edittext1d = findViewById(R.id.edittext1d);
		textview1d = findViewById(R.id.textview1d);
		edittext2d = findViewById(R.id.edittext2d);
		textview2d = findViewById(R.id.textview2d);
		edittext_am3d = findViewById(R.id.edittext_am3d);
		textview1457 = findViewById(R.id.textview1457);
		edittext3d = findViewById(R.id.edittext3d);
		textview607 = findViewById(R.id.textview607);
		textview3d = findViewById(R.id.textview3d);
		edittext_am4d = findViewById(R.id.edittext_am4d);
		textview1426 = findViewById(R.id.textview1426);
		edittext4d = findViewById(R.id.edittext4d);
		textview1427 = findViewById(R.id.textview1427);
		textview4d = findViewById(R.id.textview4d);
		edittext_am5d = findViewById(R.id.edittext_am5d);
		textview1428 = findViewById(R.id.textview1428);
		edittext5d = findViewById(R.id.edittext5d);
		textview1429 = findViewById(R.id.textview1429);
		textview5d = findViewById(R.id.textview5d);
		edittext_am6d = findViewById(R.id.edittext_am6d);
		edittext6d = findViewById(R.id.edittext6d);
		textview1431 = findViewById(R.id.textview1431);
		textview6d = findViewById(R.id.textview6d);
		edittext_am7d = findViewById(R.id.edittext_am7d);
		textview107d = findViewById(R.id.textview107d);
		edittext7d = findViewById(R.id.edittext7d);
		textview601 = findViewById(R.id.textview601);
		textview7d = findViewById(R.id.textview7d);
		edittext_am8d = findViewById(R.id.edittext_am8d);
		textview108d = findViewById(R.id.textview108d);
		edittext8d = findViewById(R.id.edittext8d);
		textview2429 = findViewById(R.id.textview2429);
		textview8d = findViewById(R.id.textview8d);
		edittext_am9d = findViewById(R.id.edittext_am9d);
		textview611 = findViewById(R.id.textview611);
		edittext9d = findViewById(R.id.edittext9d);
		textview609 = findViewById(R.id.textview609);
		textview9d = findViewById(R.id.textview9d);
		textview2433 = findViewById(R.id.textview2433);
		edittext10d = findViewById(R.id.edittext10d);
		textview98 = findViewById(R.id.textview98);
		textview10d = findViewById(R.id.textview10d);
		textview2440 = findViewById(R.id.textview2440);
		edittext11d = findViewById(R.id.edittext11d);
		textview2383 = findViewById(R.id.textview2383);
		textview11d = findViewById(R.id.textview11d);
		textview122d = findViewById(R.id.textview122d);
		textview123d = findViewById(R.id.textview123d);
		linear222d = findViewById(R.id.linear222d);
		textview2434 = findViewById(R.id.textview2434);
		edittext43d = findViewById(R.id.edittext43d);
		edittext_am12d = findViewById(R.id.edittext_am12d);
		textview2441 = findViewById(R.id.textview2441);
		edittext12d = findViewById(R.id.edittext12d);
		textview606 = findViewById(R.id.textview606);
		textview334 = findViewById(R.id.textview334);
		textview12d = findViewById(R.id.textview12d);
		linear213d = findViewById(R.id.linear213d);
		textview133d = findViewById(R.id.textview133d);
		textview134d = findViewById(R.id.textview134d);
		textview135d = findViewById(R.id.textview135d);
		textview2442 = findViewById(R.id.textview2442);
		edittext13d = findViewById(R.id.edittext13d);
		textview2443 = findViewById(R.id.textview2443);
		textview13d = findViewById(R.id.textview13d);
		linear214d = findViewById(R.id.linear214d);
		textview144d = findViewById(R.id.textview144d);
		textview145d = findViewById(R.id.textview145d);
		textview146d = findViewById(R.id.textview146d);
		textview2447 = findViewById(R.id.textview2447);
		edittext14d = findViewById(R.id.edittext14d);
		textview2431 = findViewById(R.id.textview2431);
		textview14d = findViewById(R.id.textview14d);
	}
	
	private void initializeLogic() {
	}
	
}
