package com.my.iengineer1;

import android.animation.*;
import android.app.*;
import android.content.*;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.net.*;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.widget.*;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.DialogFragment;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import org.json.*;

public class ToipccDHolePlasteringActivity extends AppCompatActivity {
	
	private ScrollView vscroll1;
	private LinearLayout linear392;
	private LinearLayout linear713;
	private HorizontalScrollView hscroll4;
	private LinearLayout linear390;
	private HorizontalScrollView hscroll3;
	private LinearLayout linear391;
	private HorizontalScrollView hscroll84;
	private LinearLayout linear118;
	private HorizontalScrollView hscroll83;
	private LinearLayout linear120;
	private LinearLayout linear33d;
	private HorizontalScrollView hscroll88;
	private LinearLayout linear722d;
	private HorizontalScrollView hscroll85;
	private LinearLayout linear152d;
	private HorizontalScrollView hscroll86;
	private LinearLayout linear122;
	private LinearLayout linear116;
	private TextView textview666ad;
	private TextView textview667bd;
	private TextView textview668cd;
	private TextView textview555d;
	private TextView textview556d;
	private LinearLayout linear185;
	private HorizontalScrollView hscroll87;
	private LinearLayout linear721d;
	private TextView textview669dd;
	private HorizontalScrollView hscroll2;
	private LinearLayout linear125;
	private HorizontalScrollView hscroll1;
	private LinearLayout linear184;
	private ImageView close_hole_d;
	private LinearLayout linear720;
	private EditText edittext6d;
	private TextView textview1d;
	private TextView textview533;
	private TextView textview537;
	private EditText edittext7d;
	private TextView textview535;
	private TextView textview2d;
	private EditText edittext8dd;
	private TextView textview490;
	private EditText edittext8d;
	private TextView textview334;
	private TextView textview3d;
	private EditText edittext9dd;
	private TextView textview491;
	private EditText edittext9d;
	private TextView textview339;
	private TextView textview4d;
	private LinearLayout linear34;
	private HorizontalScrollView hscroll82;
	private LinearLayout linear32;
	private LinearLayout linear35;
	private TextView textview33;
	private LinearLayout linear36;
	private TextView textview35;
	private LinearLayout linear865;
	private EditText edittext35dd;
	private TextView textview34;
	private EditText edittext35d;
	private TextView textview36;
	private LinearLayout linear869;
	private EditText edittext36dd;
	private TextView textview37;
	private EditText edittext36d;
	private TextView textview38;
	private EditText edittext32d;
	private TextView textview2054;
	private TextView textview32;
	private EditText edittext5dd;
	private TextView textview531;
	private EditText edittext5d;
	private TextView textview532;
	private TextView textview11d;
	private EditText edittext10d;
	private TextView textview630;
	private TextView textview5d;
	private EditText edittext11d;
	private TextView textview343;
	private TextView textview6d;
	private Button button2d;
	private TextView textview20d;
	private EditText edittext12d;
	private TextView textview496;
	private TextView textview7d;
	private TextView textview21d;
	private EditText edittext13d;
	private TextView textview632;
	private TextView textview8d;
	private TextView textview22d;
	private EditText edittext14d;
	private TextView textview349;
	private TextView textview9d;
	private TextView textview23d;
	private EditText edittext15d;
	private TextView textview493;
	private TextView textview10d;
	
	@Override
	protected void onCreate(Bundle _savedInstanceState) {
		super.onCreate(_savedInstanceState);
		setContentView(R.layout.toipcc_d_hole_plastering);
		initialize(_savedInstanceState);
		
		
		initializeLogic();
	}
	
	private void initialize(Bundle _savedInstanceState) {
		vscroll1 = findViewById(R.id.vscroll1);
		linear392 = findViewById(R.id.linear392);
		linear713 = findViewById(R.id.linear713);
		hscroll4 = findViewById(R.id.hscroll4);
		linear390 = findViewById(R.id.linear390);
		hscroll3 = findViewById(R.id.hscroll3);
		linear391 = findViewById(R.id.linear391);
		hscroll84 = findViewById(R.id.hscroll84);
		linear118 = findViewById(R.id.linear118);
		hscroll83 = findViewById(R.id.hscroll83);
		linear120 = findViewById(R.id.linear120);
		linear33d = findViewById(R.id.linear33d);
		hscroll88 = findViewById(R.id.hscroll88);
		linear722d = findViewById(R.id.linear722d);
		hscroll85 = findViewById(R.id.hscroll85);
		linear152d = findViewById(R.id.linear152d);
		hscroll86 = findViewById(R.id.hscroll86);
		linear122 = findViewById(R.id.linear122);
		linear116 = findViewById(R.id.linear116);
		textview666ad = findViewById(R.id.textview666ad);
		textview667bd = findViewById(R.id.textview667bd);
		textview668cd = findViewById(R.id.textview668cd);
		textview555d = findViewById(R.id.textview555d);
		textview556d = findViewById(R.id.textview556d);
		linear185 = findViewById(R.id.linear185);
		hscroll87 = findViewById(R.id.hscroll87);
		linear721d = findViewById(R.id.linear721d);
		textview669dd = findViewById(R.id.textview669dd);
		hscroll2 = findViewById(R.id.hscroll2);
		linear125 = findViewById(R.id.linear125);
		hscroll1 = findViewById(R.id.hscroll1);
		linear184 = findViewById(R.id.linear184);
		close_hole_d = findViewById(R.id.close_hole_d);
		linear720 = findViewById(R.id.linear720);
		edittext6d = findViewById(R.id.edittext6d);
		textview1d = findViewById(R.id.textview1d);
		textview533 = findViewById(R.id.textview533);
		textview537 = findViewById(R.id.textview537);
		edittext7d = findViewById(R.id.edittext7d);
		textview535 = findViewById(R.id.textview535);
		textview2d = findViewById(R.id.textview2d);
		edittext8dd = findViewById(R.id.edittext8dd);
		textview490 = findViewById(R.id.textview490);
		edittext8d = findViewById(R.id.edittext8d);
		textview334 = findViewById(R.id.textview334);
		textview3d = findViewById(R.id.textview3d);
		edittext9dd = findViewById(R.id.edittext9dd);
		textview491 = findViewById(R.id.textview491);
		edittext9d = findViewById(R.id.edittext9d);
		textview339 = findViewById(R.id.textview339);
		textview4d = findViewById(R.id.textview4d);
		linear34 = findViewById(R.id.linear34);
		hscroll82 = findViewById(R.id.hscroll82);
		linear32 = findViewById(R.id.linear32);
		linear35 = findViewById(R.id.linear35);
		textview33 = findViewById(R.id.textview33);
		linear36 = findViewById(R.id.linear36);
		textview35 = findViewById(R.id.textview35);
		linear865 = findViewById(R.id.linear865);
		edittext35dd = findViewById(R.id.edittext35dd);
		textview34 = findViewById(R.id.textview34);
		edittext35d = findViewById(R.id.edittext35d);
		textview36 = findViewById(R.id.textview36);
		linear869 = findViewById(R.id.linear869);
		edittext36dd = findViewById(R.id.edittext36dd);
		textview37 = findViewById(R.id.textview37);
		edittext36d = findViewById(R.id.edittext36d);
		textview38 = findViewById(R.id.textview38);
		edittext32d = findViewById(R.id.edittext32d);
		textview2054 = findViewById(R.id.textview2054);
		textview32 = findViewById(R.id.textview32);
		edittext5dd = findViewById(R.id.edittext5dd);
		textview531 = findViewById(R.id.textview531);
		edittext5d = findViewById(R.id.edittext5d);
		textview532 = findViewById(R.id.textview532);
		textview11d = findViewById(R.id.textview11d);
		edittext10d = findViewById(R.id.edittext10d);
		textview630 = findViewById(R.id.textview630);
		textview5d = findViewById(R.id.textview5d);
		edittext11d = findViewById(R.id.edittext11d);
		textview343 = findViewById(R.id.textview343);
		textview6d = findViewById(R.id.textview6d);
		button2d = findViewById(R.id.button2d);
		textview20d = findViewById(R.id.textview20d);
		edittext12d = findViewById(R.id.edittext12d);
		textview496 = findViewById(R.id.textview496);
		textview7d = findViewById(R.id.textview7d);
		textview21d = findViewById(R.id.textview21d);
		edittext13d = findViewById(R.id.edittext13d);
		textview632 = findViewById(R.id.textview632);
		textview8d = findViewById(R.id.textview8d);
		textview22d = findViewById(R.id.textview22d);
		edittext14d = findViewById(R.id.edittext14d);
		textview349 = findViewById(R.id.textview349);
		textview9d = findViewById(R.id.textview9d);
		textview23d = findViewById(R.id.textview23d);
		edittext15d = findViewById(R.id.edittext15d);
		textview493 = findViewById(R.id.textview493);
		textview10d = findViewById(R.id.textview10d);
	}
	
	private void initializeLogic() {
	}
	
}
