package com.my.iengineer1;

import android.animation.*;
import android.app.*;
import android.content.*;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.net.*;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.widget.*;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.DialogFragment;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import org.json.*;

public class ToipDPipeLineLengthDifferencesActivity extends AppCompatActivity {
	
	private ScrollView vscroll1d;
	private LinearLayout dynamic_linear0d;
	private LinearLayout linear_close;
	private HorizontalScrollView hscroll1d;
	private LinearLayout linear1d;
	private HorizontalScrollView hscroll2d;
	private LinearLayout linear2d;
	private HorizontalScrollView hscroll3d;
	private LinearLayout linear3d;
	private HorizontalScrollView hscroll204;
	private TextView textview201d;
	private TextView textview202d;
	private LinearLayout linear4d;
	private LinearLayout linear202d;
	private HorizontalScrollView hscroll10d;
	private TextView textview203d;
	private LinearLayout linear8d;
	private LinearLayout linear203d;
	private HorizontalScrollView hscroll11d;
	private TextView textview2466;
	private LinearLayout linear12d;
	private HorizontalScrollView hscroll14d;
	private LinearLayout linear13d;
	private HorizontalScrollView hscroll205;
	private TextView textview204d;
	private LinearLayout linear204d;
	private LinearLayout linear_dynamic_short_piece;
	private Button add_dynamic_short_piece;
	private LinearLayout linear104s1;
	private LinearLayout linear205d;
	private LinearLayout linear206d;
	private HorizontalScrollView hscroll16;
	private LinearLayout linear27d;
	private LinearLayout linear28d;
	private LinearLayout linear29d;
	private LinearLayout linear32d;
	private LinearLayout linear33d;
	private LinearLayout linear34d;
	private LinearLayout linear30d;
	private LinearLayout linear31d;
	private LinearLayout linear35d;
	private LinearLayout linear36d;
	private LinearLayout linear37d;
	private LinearLayout linear38d;
	private LinearLayout linear39d;
	private LinearLayout linear40d;
	private LinearLayout linear41d;
	private HorizontalScrollView hscroll207;
	private LinearLayout linear48d;
	private LinearLayout linear42d;
	private HorizontalScrollView hscroll208;
	private LinearLayout linear49d;
	private HorizontalScrollView hscroll209;
	private LinearLayout linear50d;
	private ImageView close1d;
	private HorizontalScrollView hscroll211;
	private ImageView print1d;
	private LinearLayout linear720;
	private EditText edittext1d;
	private TextView textview1d;
	private TextView textview1155;
	private EditText edittext2d;
	private TextView textview1156;
	private TextView textview2d;
	private EditText edittext_am3d;
	private TextView textview531;
	private EditText edittext3d;
	private TextView textview532;
	private TextView textview3d;
	private EditText edittext4d;
	private TextView textview280;
	private TextView textview4d;
	private LinearLayout linear7d;
	private TextView textview644;
	private LinearLayout linear6d;
	private TextView textview642;
	private LinearLayout linear5d;
	private TextView textview7d;
	private EditText edittext7d;
	private EditText edittext_am7d;
	private TextView textview6d;
	private EditText edittext6d;
	private EditText edittext_am6d;
	private TextView textview5d;
	private EditText edittext5d;
	private EditText edittext_am5d;
	private EditText edittext8d;
	private TextView textview2457;
	private TextView textview8d;
	private LinearLayout linear11d;
	private TextView textview2455;
	private LinearLayout linear10d;
	private TextView textview2454;
	private LinearLayout linear9d;
	private TextView textview11d;
	private EditText edittext11d;
	private EditText edittext_am11d;
	private TextView textview10d;
	private EditText edittext10d;
	private EditText edittext_am10d;
	private TextView textview9d;
	private EditText edittext9d;
	private EditText edittext_am9d;
	private EditText edittext_am12d;
	private TextView textview123;
	private EditText edittext12d;
	private TextView textview403;
	private TextView textview12d;
	private EditText edittext_am13d;
	private TextView textview612;
	private EditText edittext13d;
	private TextView textview592;
	private TextView textview13d;
	private ImageView close2d;
	private LinearLayout linear15d;
	private TextView textview1431;
	private LinearLayout linear14d;
	private TextView textview15d;
	private EditText edittext15d;
	private EditText edittext_am15d;
	private TextView textview14d;
	private EditText edittext14d;
	private EditText edittext_am14d;
	private Button button1d;
	private LinearLayout linear2233;
	private LinearLayout linear2232;
	private EditText edittext17d;
	private TextView textview17d;
	private TextView textview2456;
	private EditText edittext16d;
	private TextView textview16d;
	private EditText edittext19d;
	private TextView textview19d;
	private TextView textview606;
	private EditText edittext18d;
	private TextView textview18d;
	private HorizontalScrollView hscroll206;
	private LinearLayout linear2236;
	private LinearLayout linear2239;
	private LinearLayout linear2235;
	private EditText edittext22d;
	private TextView textview22d;
	private TextView textview2465;
	private EditText edittext21d;
	private TextView textview21d;
	private TextView textview2459;
	private EditText edittext20d;
	private TextView textview20d;
	private EditText edittext24d;
	private TextView textview24d;
	private TextView textview2462;
	private EditText edittext23d;
	private TextView textview23d;
	private EditText edittext26d;
	private TextView textview26d;
	private TextView textview2474;
	private EditText edittext25d;
	private TextView textview25d;
	private EditText edittext27d;
	private TextView textview27d;
	private EditText edittext28d;
	private TextView textview28d;
	private EditText edittext29d;
	private TextView textview29d;
	private TextView textview400;
	private EditText edittext32d;
	private TextView textview334;
	private TextView textview32d;
	private TextView textview1169;
	private EditText edittext33d;
	private TextView textview1170;
	private TextView textview33d;
	private TextView textview399;
	private EditText edittext34d;
	private TextView textview342;
	private TextView textview34d;
	private EditText edittext30d;
	private TextView textview30d;
	private EditText edittext31d;
	private TextView textview31d;
	private TextView textview1139;
	private EditText edittext35d;
	private TextView textview346;
	private TextView textview35d;
	private TextView textview629;
	private EditText edittext36d;
	private TextView textview630;
	private TextView textview36d;
	private TextView textview1141;
	private EditText edittext37d;
	private TextView textview357;
	private TextView textview37d;
	private TextView textview1142;
	private EditText edittext38d;
	private TextView textview365;
	private TextView textview38d;
	private TextView textview2475;
	private EditText edittext39d;
	private TextView textview2476;
	private TextView textview39d;
	private TextView textview2478;
	private EditText edittext40d;
	private TextView textview2479;
	private TextView textview40d;
	private EditText edittext41d;
	private TextView textview41d;
	private TextView textview2481;
	private EditText edittext48d;
	private TextView textview2482;
	private TextView textview48d;
	private EditText edittext42d;
	private TextView textview42d;
	private TextView textview601;
	private EditText edittext49d;
	private TextView textview602;
	private TextView textview49d;
	private TextView textview1136;
	private EditText edittext50d;
	private TextView textview596;
	private TextView textview50d;
	
	@Override
	protected void onCreate(Bundle _savedInstanceState) {
		super.onCreate(_savedInstanceState);
		setContentView(R.layout.toip_d_pipe_line_length_differences);
		initialize(_savedInstanceState);
		
		
		initializeLogic();
	}
	
	private void initialize(Bundle _savedInstanceState) {
		vscroll1d = findViewById(R.id.vscroll1d);
		dynamic_linear0d = findViewById(R.id.dynamic_linear0d);
		linear_close = findViewById(R.id.linear_close);
		hscroll1d = findViewById(R.id.hscroll1d);
		linear1d = findViewById(R.id.linear1d);
		hscroll2d = findViewById(R.id.hscroll2d);
		linear2d = findViewById(R.id.linear2d);
		hscroll3d = findViewById(R.id.hscroll3d);
		linear3d = findViewById(R.id.linear3d);
		hscroll204 = findViewById(R.id.hscroll204);
		textview201d = findViewById(R.id.textview201d);
		textview202d = findViewById(R.id.textview202d);
		linear4d = findViewById(R.id.linear4d);
		linear202d = findViewById(R.id.linear202d);
		hscroll10d = findViewById(R.id.hscroll10d);
		textview203d = findViewById(R.id.textview203d);
		linear8d = findViewById(R.id.linear8d);
		linear203d = findViewById(R.id.linear203d);
		hscroll11d = findViewById(R.id.hscroll11d);
		textview2466 = findViewById(R.id.textview2466);
		linear12d = findViewById(R.id.linear12d);
		hscroll14d = findViewById(R.id.hscroll14d);
		linear13d = findViewById(R.id.linear13d);
		hscroll205 = findViewById(R.id.hscroll205);
		textview204d = findViewById(R.id.textview204d);
		linear204d = findViewById(R.id.linear204d);
		linear_dynamic_short_piece = findViewById(R.id.linear_dynamic_short_piece);
		add_dynamic_short_piece = findViewById(R.id.add_dynamic_short_piece);
		linear104s1 = findViewById(R.id.linear104s1);
		linear205d = findViewById(R.id.linear205d);
		linear206d = findViewById(R.id.linear206d);
		hscroll16 = findViewById(R.id.hscroll16);
		linear27d = findViewById(R.id.linear27d);
		linear28d = findViewById(R.id.linear28d);
		linear29d = findViewById(R.id.linear29d);
		linear32d = findViewById(R.id.linear32d);
		linear33d = findViewById(R.id.linear33d);
		linear34d = findViewById(R.id.linear34d);
		linear30d = findViewById(R.id.linear30d);
		linear31d = findViewById(R.id.linear31d);
		linear35d = findViewById(R.id.linear35d);
		linear36d = findViewById(R.id.linear36d);
		linear37d = findViewById(R.id.linear37d);
		linear38d = findViewById(R.id.linear38d);
		linear39d = findViewById(R.id.linear39d);
		linear40d = findViewById(R.id.linear40d);
		linear41d = findViewById(R.id.linear41d);
		hscroll207 = findViewById(R.id.hscroll207);
		linear48d = findViewById(R.id.linear48d);
		linear42d = findViewById(R.id.linear42d);
		hscroll208 = findViewById(R.id.hscroll208);
		linear49d = findViewById(R.id.linear49d);
		hscroll209 = findViewById(R.id.hscroll209);
		linear50d = findViewById(R.id.linear50d);
		close1d = findViewById(R.id.close1d);
		hscroll211 = findViewById(R.id.hscroll211);
		print1d = findViewById(R.id.print1d);
		linear720 = findViewById(R.id.linear720);
		edittext1d = findViewById(R.id.edittext1d);
		textview1d = findViewById(R.id.textview1d);
		textview1155 = findViewById(R.id.textview1155);
		edittext2d = findViewById(R.id.edittext2d);
		textview1156 = findViewById(R.id.textview1156);
		textview2d = findViewById(R.id.textview2d);
		edittext_am3d = findViewById(R.id.edittext_am3d);
		textview531 = findViewById(R.id.textview531);
		edittext3d = findViewById(R.id.edittext3d);
		textview532 = findViewById(R.id.textview532);
		textview3d = findViewById(R.id.textview3d);
		edittext4d = findViewById(R.id.edittext4d);
		textview280 = findViewById(R.id.textview280);
		textview4d = findViewById(R.id.textview4d);
		linear7d = findViewById(R.id.linear7d);
		textview644 = findViewById(R.id.textview644);
		linear6d = findViewById(R.id.linear6d);
		textview642 = findViewById(R.id.textview642);
		linear5d = findViewById(R.id.linear5d);
		textview7d = findViewById(R.id.textview7d);
		edittext7d = findViewById(R.id.edittext7d);
		edittext_am7d = findViewById(R.id.edittext_am7d);
		textview6d = findViewById(R.id.textview6d);
		edittext6d = findViewById(R.id.edittext6d);
		edittext_am6d = findViewById(R.id.edittext_am6d);
		textview5d = findViewById(R.id.textview5d);
		edittext5d = findViewById(R.id.edittext5d);
		edittext_am5d = findViewById(R.id.edittext_am5d);
		edittext8d = findViewById(R.id.edittext8d);
		textview2457 = findViewById(R.id.textview2457);
		textview8d = findViewById(R.id.textview8d);
		linear11d = findViewById(R.id.linear11d);
		textview2455 = findViewById(R.id.textview2455);
		linear10d = findViewById(R.id.linear10d);
		textview2454 = findViewById(R.id.textview2454);
		linear9d = findViewById(R.id.linear9d);
		textview11d = findViewById(R.id.textview11d);
		edittext11d = findViewById(R.id.edittext11d);
		edittext_am11d = findViewById(R.id.edittext_am11d);
		textview10d = findViewById(R.id.textview10d);
		edittext10d = findViewById(R.id.edittext10d);
		edittext_am10d = findViewById(R.id.edittext_am10d);
		textview9d = findViewById(R.id.textview9d);
		edittext9d = findViewById(R.id.edittext9d);
		edittext_am9d = findViewById(R.id.edittext_am9d);
		edittext_am12d = findViewById(R.id.edittext_am12d);
		textview123 = findViewById(R.id.textview123);
		edittext12d = findViewById(R.id.edittext12d);
		textview403 = findViewById(R.id.textview403);
		textview12d = findViewById(R.id.textview12d);
		edittext_am13d = findViewById(R.id.edittext_am13d);
		textview612 = findViewById(R.id.textview612);
		edittext13d = findViewById(R.id.edittext13d);
		textview592 = findViewById(R.id.textview592);
		textview13d = findViewById(R.id.textview13d);
		close2d = findViewById(R.id.close2d);
		linear15d = findViewById(R.id.linear15d);
		textview1431 = findViewById(R.id.textview1431);
		linear14d = findViewById(R.id.linear14d);
		textview15d = findViewById(R.id.textview15d);
		edittext15d = findViewById(R.id.edittext15d);
		edittext_am15d = findViewById(R.id.edittext_am15d);
		textview14d = findViewById(R.id.textview14d);
		edittext14d = findViewById(R.id.edittext14d);
		edittext_am14d = findViewById(R.id.edittext_am14d);
		button1d = findViewById(R.id.button1d);
		linear2233 = findViewById(R.id.linear2233);
		linear2232 = findViewById(R.id.linear2232);
		edittext17d = findViewById(R.id.edittext17d);
		textview17d = findViewById(R.id.textview17d);
		textview2456 = findViewById(R.id.textview2456);
		edittext16d = findViewById(R.id.edittext16d);
		textview16d = findViewById(R.id.textview16d);
		edittext19d = findViewById(R.id.edittext19d);
		textview19d = findViewById(R.id.textview19d);
		textview606 = findViewById(R.id.textview606);
		edittext18d = findViewById(R.id.edittext18d);
		textview18d = findViewById(R.id.textview18d);
		hscroll206 = findViewById(R.id.hscroll206);
		linear2236 = findViewById(R.id.linear2236);
		linear2239 = findViewById(R.id.linear2239);
		linear2235 = findViewById(R.id.linear2235);
		edittext22d = findViewById(R.id.edittext22d);
		textview22d = findViewById(R.id.textview22d);
		textview2465 = findViewById(R.id.textview2465);
		edittext21d = findViewById(R.id.edittext21d);
		textview21d = findViewById(R.id.textview21d);
		textview2459 = findViewById(R.id.textview2459);
		edittext20d = findViewById(R.id.edittext20d);
		textview20d = findViewById(R.id.textview20d);
		edittext24d = findViewById(R.id.edittext24d);
		textview24d = findViewById(R.id.textview24d);
		textview2462 = findViewById(R.id.textview2462);
		edittext23d = findViewById(R.id.edittext23d);
		textview23d = findViewById(R.id.textview23d);
		edittext26d = findViewById(R.id.edittext26d);
		textview26d = findViewById(R.id.textview26d);
		textview2474 = findViewById(R.id.textview2474);
		edittext25d = findViewById(R.id.edittext25d);
		textview25d = findViewById(R.id.textview25d);
		edittext27d = findViewById(R.id.edittext27d);
		textview27d = findViewById(R.id.textview27d);
		edittext28d = findViewById(R.id.edittext28d);
		textview28d = findViewById(R.id.textview28d);
		edittext29d = findViewById(R.id.edittext29d);
		textview29d = findViewById(R.id.textview29d);
		textview400 = findViewById(R.id.textview400);
		edittext32d = findViewById(R.id.edittext32d);
		textview334 = findViewById(R.id.textview334);
		textview32d = findViewById(R.id.textview32d);
		textview1169 = findViewById(R.id.textview1169);
		edittext33d = findViewById(R.id.edittext33d);
		textview1170 = findViewById(R.id.textview1170);
		textview33d = findViewById(R.id.textview33d);
		textview399 = findViewById(R.id.textview399);
		edittext34d = findViewById(R.id.edittext34d);
		textview342 = findViewById(R.id.textview342);
		textview34d = findViewById(R.id.textview34d);
		edittext30d = findViewById(R.id.edittext30d);
		textview30d = findViewById(R.id.textview30d);
		edittext31d = findViewById(R.id.edittext31d);
		textview31d = findViewById(R.id.textview31d);
		textview1139 = findViewById(R.id.textview1139);
		edittext35d = findViewById(R.id.edittext35d);
		textview346 = findViewById(R.id.textview346);
		textview35d = findViewById(R.id.textview35d);
		textview629 = findViewById(R.id.textview629);
		edittext36d = findViewById(R.id.edittext36d);
		textview630 = findViewById(R.id.textview630);
		textview36d = findViewById(R.id.textview36d);
		textview1141 = findViewById(R.id.textview1141);
		edittext37d = findViewById(R.id.edittext37d);
		textview357 = findViewById(R.id.textview357);
		textview37d = findViewById(R.id.textview37d);
		textview1142 = findViewById(R.id.textview1142);
		edittext38d = findViewById(R.id.edittext38d);
		textview365 = findViewById(R.id.textview365);
		textview38d = findViewById(R.id.textview38d);
		textview2475 = findViewById(R.id.textview2475);
		edittext39d = findViewById(R.id.edittext39d);
		textview2476 = findViewById(R.id.textview2476);
		textview39d = findViewById(R.id.textview39d);
		textview2478 = findViewById(R.id.textview2478);
		edittext40d = findViewById(R.id.edittext40d);
		textview2479 = findViewById(R.id.textview2479);
		textview40d = findViewById(R.id.textview40d);
		edittext41d = findViewById(R.id.edittext41d);
		textview41d = findViewById(R.id.textview41d);
		textview2481 = findViewById(R.id.textview2481);
		edittext48d = findViewById(R.id.edittext48d);
		textview2482 = findViewById(R.id.textview2482);
		textview48d = findViewById(R.id.textview48d);
		edittext42d = findViewById(R.id.edittext42d);
		textview42d = findViewById(R.id.textview42d);
		textview601 = findViewById(R.id.textview601);
		edittext49d = findViewById(R.id.edittext49d);
		textview602 = findViewById(R.id.textview602);
		textview49d = findViewById(R.id.textview49d);
		textview1136 = findViewById(R.id.textview1136);
		edittext50d = findViewById(R.id.edittext50d);
		textview596 = findViewById(R.id.textview596);
		textview50d = findViewById(R.id.textview50d);
	}
	
	private void initializeLogic() {
	}
	
}
