package com.my.iengineer1;

import android.animation.*;
import android.app.*;
import android.content.*;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.net.*;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.widget.*;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.DialogFragment;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import org.json.*;

public class ToipDDrainagePipeLineDepthActivity extends AppCompatActivity {
	
	private TextView textview519;
	private ScrollView vscroll1;
	private LinearLayout linear1;
	private LinearLayout linear507;
	private LinearLayout linear509;
	private LinearLayout linear195;
	private LinearLayout linear201;
	private LinearLayout linear198;
	private LinearLayout linear202;
	private LinearLayout linear196;
	private LinearLayout linear203;
	private LinearLayout linear197;
	private HorizontalScrollView hscroll8;
	private LinearLayout linear74;
	private LinearLayout linear204;
	private LinearLayout linear200;
	private ImageView close;
	private LinearLayout linear508;
	private EditText edittext1d;
	private TextView textview603;
	private TextView textview604;
	private TextView textview614;
	private EditText edittext14d;
	private TextView textview612;
	private TextView textview613;
	private TextView textview14;
	private EditText edittext2d;
	private TextView textview607;
	private TextView textview608;
	private TextView textview611;
	private EditText edittext3d;
	private TextView textview609;
	private TextView textview610;
	private LinearLayout linear40;
	private LinearLayout linear43;
	private TextView textview122;
	private LinearLayout linear77;
	private TextView textview58;
	private LinearLayout linear127;
	private LinearLayout linear125;
	private LinearLayout linear126;
	private LinearLayout linear157;
	private EditText edittext4d;
	private TextView textview354;
	private EditText edittext5d;
	private TextView textview601;
	private TextView textview136;
	private EditText edittext6d;
	private TextView textview353;
	private TextView textview60;
	private TextView textview605;
	private EditText edittext7d;
	private TextView textview405;
	private TextView textview406;
	private TextView textview123;
	private LinearLayout linear121;
	private LinearLayout linear119;
	private LinearLayout linear120;
	private LinearLayout linear118;
	private EditText edittext8d;
	private TextView textview341;
	private EditText edittext9d;
	private TextView textview592;
	private TextView textview135;
	private EditText edittext10d;
	private TextView textview340;
	private TextView textview138;
	private TextView textview606;
	private EditText edittext11d;
	private TextView textview334;
	private TextView textview335;
	private TextView textview467;
	private EditText edittext12d;
	private TextView textview286;
	private TextView textview112;
	private LinearLayout linear199;
	private TextView textview2d;
	private TextView textview531;
	private EditText edittext13d;
	private TextView textview532;
	private TextView textview533;
	
	@Override
	protected void onCreate(Bundle _savedInstanceState) {
		super.onCreate(_savedInstanceState);
		setContentView(R.layout.toip_d_drainage_pipe_line_depth);
		initialize(_savedInstanceState);
		
		
		initializeLogic();
	}
	
	private void initialize(Bundle _savedInstanceState) {
		textview519 = findViewById(R.id.textview519);
		vscroll1 = findViewById(R.id.vscroll1);
		linear1 = findViewById(R.id.linear1);
		linear507 = findViewById(R.id.linear507);
		linear509 = findViewById(R.id.linear509);
		linear195 = findViewById(R.id.linear195);
		linear201 = findViewById(R.id.linear201);
		linear198 = findViewById(R.id.linear198);
		linear202 = findViewById(R.id.linear202);
		linear196 = findViewById(R.id.linear196);
		linear203 = findViewById(R.id.linear203);
		linear197 = findViewById(R.id.linear197);
		hscroll8 = findViewById(R.id.hscroll8);
		linear74 = findViewById(R.id.linear74);
		linear204 = findViewById(R.id.linear204);
		linear200 = findViewById(R.id.linear200);
		close = findViewById(R.id.close);
		linear508 = findViewById(R.id.linear508);
		edittext1d = findViewById(R.id.edittext1d);
		textview603 = findViewById(R.id.textview603);
		textview604 = findViewById(R.id.textview604);
		textview614 = findViewById(R.id.textview614);
		edittext14d = findViewById(R.id.edittext14d);
		textview612 = findViewById(R.id.textview612);
		textview613 = findViewById(R.id.textview613);
		textview14 = findViewById(R.id.textview14);
		edittext2d = findViewById(R.id.edittext2d);
		textview607 = findViewById(R.id.textview607);
		textview608 = findViewById(R.id.textview608);
		textview611 = findViewById(R.id.textview611);
		edittext3d = findViewById(R.id.edittext3d);
		textview609 = findViewById(R.id.textview609);
		textview610 = findViewById(R.id.textview610);
		linear40 = findViewById(R.id.linear40);
		linear43 = findViewById(R.id.linear43);
		textview122 = findViewById(R.id.textview122);
		linear77 = findViewById(R.id.linear77);
		textview58 = findViewById(R.id.textview58);
		linear127 = findViewById(R.id.linear127);
		linear125 = findViewById(R.id.linear125);
		linear126 = findViewById(R.id.linear126);
		linear157 = findViewById(R.id.linear157);
		edittext4d = findViewById(R.id.edittext4d);
		textview354 = findViewById(R.id.textview354);
		edittext5d = findViewById(R.id.edittext5d);
		textview601 = findViewById(R.id.textview601);
		textview136 = findViewById(R.id.textview136);
		edittext6d = findViewById(R.id.edittext6d);
		textview353 = findViewById(R.id.textview353);
		textview60 = findViewById(R.id.textview60);
		textview605 = findViewById(R.id.textview605);
		edittext7d = findViewById(R.id.edittext7d);
		textview405 = findViewById(R.id.textview405);
		textview406 = findViewById(R.id.textview406);
		textview123 = findViewById(R.id.textview123);
		linear121 = findViewById(R.id.linear121);
		linear119 = findViewById(R.id.linear119);
		linear120 = findViewById(R.id.linear120);
		linear118 = findViewById(R.id.linear118);
		edittext8d = findViewById(R.id.edittext8d);
		textview341 = findViewById(R.id.textview341);
		edittext9d = findViewById(R.id.edittext9d);
		textview592 = findViewById(R.id.textview592);
		textview135 = findViewById(R.id.textview135);
		edittext10d = findViewById(R.id.edittext10d);
		textview340 = findViewById(R.id.textview340);
		textview138 = findViewById(R.id.textview138);
		textview606 = findViewById(R.id.textview606);
		edittext11d = findViewById(R.id.edittext11d);
		textview334 = findViewById(R.id.textview334);
		textview335 = findViewById(R.id.textview335);
		textview467 = findViewById(R.id.textview467);
		edittext12d = findViewById(R.id.edittext12d);
		textview286 = findViewById(R.id.textview286);
		textview112 = findViewById(R.id.textview112);
		linear199 = findViewById(R.id.linear199);
		textview2d = findViewById(R.id.textview2d);
		textview531 = findViewById(R.id.textview531);
		edittext13d = findViewById(R.id.edittext13d);
		textview532 = findViewById(R.id.textview532);
		textview533 = findViewById(R.id.textview533);
	}
	
	private void initializeLogic() {
	}
	
}
