package com.my.iengineer1;

import android.animation.*;
import android.app.*;
import android.content.*;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.net.*;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.widget.*;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.DialogFragment;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import org.json.*;

public class ToipDPipeLineLengthDifferenceActivity extends AppCompatActivity {
	
	private TextView textview519;
	private ScrollView vscroll1;
	private LinearLayout dynamic_linear4p;
	private LinearLayout linear5;
	private TextView textview1158;
	private LinearLayout linear144;
	private TextView textview1149;
	private LinearLayout linear2;
	private TextView textview614;
	private HorizontalScrollView hscroll1;
	private TextView textview126;
	private LinearLayout linear7;
	private LinearLayout linear101s1;
	private LinearLayout linear8;
	private LinearLayout linear417;
	private LinearLayout linear9;
	private TextView textview1137;
	private LinearLayout linear153d;
	private TextView textview112d;
	private LinearLayout linear152d;
	private TextView textview111d;
	private LinearLayout linear10;
	private LinearLayout linear104s1;
	private LinearLayout dynamic_linear11p;
	private LinearLayout dynamic_linear12p;
	private LinearLayout dynamic_linear13p;
	private LinearLayout dynamic_linear14p;
	private LinearLayout dynamic_linear15p;
	private LinearLayout dynamic_linear16p;
	private TextView textview1146;
	private LinearLayout linear17;
	private TextView textview1153;
	private Button dynamic_button2p;
	private TextView textview1154;
	private LinearLayout dynamic_linear18p;
	private TextView textview1152;
	private LinearLayout dynamic_linear19p;
	private LinearLayout add_dynamic_element_lin;
	private EditText dynamic_edittext1p;
	private TextView textview1;
	private TextView textview1155;
	private EditText edittext94;
	private TextView textview1156;
	private TextView textview1157;
	private EditText edittext2d;
	private TextView textview531;
	private EditText dynamic_edittext2p;
	private TextView textview532;
	private TextView dynamic_textview2p;
	private LinearLayout linear3;
	private LinearLayout linear416;
	private TextView textview1134;
	private LinearLayout linear415;
	private TextView textview3;
	private EditText dynamic_edittext3p;
	private TextView textview140;
	private TextView dynamic_textview5p;
	private TextView textview374;
	private EditText dynamic_edittext5p;
	private TextView textview4;
	private EditText dynamic_edittext4p;
	private TextView textview150;
	private TextView dynamic_textview6p;
	private TextView textview124;
	private EditText dynamic_edittext6p;
	private TextView textview1135;
	private EditText dynamic_edittext7p;
	private TextView textview280;
	private TextView dynamic_textview7p;
	private TextView textview123;
	private EditText dynamic_edittext8p;
	private TextView textview403;
	private TextView dynamic_textview8p;
	private TextView textview612;
	private EditText dynamic_edittext9p;
	private TextView textview592;
	private TextView dynamic_textview9p;
	private TextView textview1169;
	private EditText edittext23d;
	private TextView textview1170;
	private TextView textview1171;
	private TextView textview629;
	private EditText edittext22d;
	private TextView textview630;
	private TextView textview631;
	private TextView textview1136;
	private EditText dynamic_edittext10p;
	private TextView textview593;
	private TextView dynamic_textview10p;
	private Button dynamic_button1p;
	private TextView textview400;
	private EditText dynamic_edittext11p;
	private TextView textview334;
	private TextView textview11;
	private TextView textview399;
	private EditText dynamic_edittext12p;
	private TextView textview342;
	private TextView textview12;
	private TextView textview1139;
	private EditText dynamic_edittext13p;
	private TextView textview346;
	private TextView textview13;
	private TextView textview1140;
	private EditText dynamic_edittext14p;
	private TextView textview596;
	private TextView textview14;
	private TextView textview1141;
	private EditText dynamic_edittext15p;
	private TextView textview357;
	private TextView textview15;
	private TextView textview1142;
	private EditText dynamic_edittext16p;
	private TextView textview365;
	private TextView textview16;
	private TextView textview1147;
	private EditText dynamic_edittext17p;
	private TextView textview597;
	private TextView textview17;
	private TextView textview1150;
	private EditText dynamic_edittext18p;
	private TextView textview1151;
	private TextView textview533;
	private TextView textview601;
	private EditText dynamic_edittext19p;
	private TextView textview602;
	private TextView textview603;
	private Button dynamic_remove;
	private TextView textview704;
	
	@Override
	protected void onCreate(Bundle _savedInstanceState) {
		super.onCreate(_savedInstanceState);
		setContentView(R.layout.toip_d_pipe_line_length_difference);
		initialize(_savedInstanceState);
		
		
		initializeLogic();
	}
	
	private void initialize(Bundle _savedInstanceState) {
		textview519 = findViewById(R.id.textview519);
		vscroll1 = findViewById(R.id.vscroll1);
		dynamic_linear4p = findViewById(R.id.dynamic_linear4p);
		linear5 = findViewById(R.id.linear5);
		textview1158 = findViewById(R.id.textview1158);
		linear144 = findViewById(R.id.linear144);
		textview1149 = findViewById(R.id.textview1149);
		linear2 = findViewById(R.id.linear2);
		textview614 = findViewById(R.id.textview614);
		hscroll1 = findViewById(R.id.hscroll1);
		textview126 = findViewById(R.id.textview126);
		linear7 = findViewById(R.id.linear7);
		linear101s1 = findViewById(R.id.linear101s1);
		linear8 = findViewById(R.id.linear8);
		linear417 = findViewById(R.id.linear417);
		linear9 = findViewById(R.id.linear9);
		textview1137 = findViewById(R.id.textview1137);
		linear153d = findViewById(R.id.linear153d);
		textview112d = findViewById(R.id.textview112d);
		linear152d = findViewById(R.id.linear152d);
		textview111d = findViewById(R.id.textview111d);
		linear10 = findViewById(R.id.linear10);
		linear104s1 = findViewById(R.id.linear104s1);
		dynamic_linear11p = findViewById(R.id.dynamic_linear11p);
		dynamic_linear12p = findViewById(R.id.dynamic_linear12p);
		dynamic_linear13p = findViewById(R.id.dynamic_linear13p);
		dynamic_linear14p = findViewById(R.id.dynamic_linear14p);
		dynamic_linear15p = findViewById(R.id.dynamic_linear15p);
		dynamic_linear16p = findViewById(R.id.dynamic_linear16p);
		textview1146 = findViewById(R.id.textview1146);
		linear17 = findViewById(R.id.linear17);
		textview1153 = findViewById(R.id.textview1153);
		dynamic_button2p = findViewById(R.id.dynamic_button2p);
		textview1154 = findViewById(R.id.textview1154);
		dynamic_linear18p = findViewById(R.id.dynamic_linear18p);
		textview1152 = findViewById(R.id.textview1152);
		dynamic_linear19p = findViewById(R.id.dynamic_linear19p);
		add_dynamic_element_lin = findViewById(R.id.add_dynamic_element_lin);
		dynamic_edittext1p = findViewById(R.id.dynamic_edittext1p);
		textview1 = findViewById(R.id.textview1);
		textview1155 = findViewById(R.id.textview1155);
		edittext94 = findViewById(R.id.edittext94);
		textview1156 = findViewById(R.id.textview1156);
		textview1157 = findViewById(R.id.textview1157);
		edittext2d = findViewById(R.id.edittext2d);
		textview531 = findViewById(R.id.textview531);
		dynamic_edittext2p = findViewById(R.id.dynamic_edittext2p);
		textview532 = findViewById(R.id.textview532);
		dynamic_textview2p = findViewById(R.id.dynamic_textview2p);
		linear3 = findViewById(R.id.linear3);
		linear416 = findViewById(R.id.linear416);
		textview1134 = findViewById(R.id.textview1134);
		linear415 = findViewById(R.id.linear415);
		textview3 = findViewById(R.id.textview3);
		dynamic_edittext3p = findViewById(R.id.dynamic_edittext3p);
		textview140 = findViewById(R.id.textview140);
		dynamic_textview5p = findViewById(R.id.dynamic_textview5p);
		textview374 = findViewById(R.id.textview374);
		dynamic_edittext5p = findViewById(R.id.dynamic_edittext5p);
		textview4 = findViewById(R.id.textview4);
		dynamic_edittext4p = findViewById(R.id.dynamic_edittext4p);
		textview150 = findViewById(R.id.textview150);
		dynamic_textview6p = findViewById(R.id.dynamic_textview6p);
		textview124 = findViewById(R.id.textview124);
		dynamic_edittext6p = findViewById(R.id.dynamic_edittext6p);
		textview1135 = findViewById(R.id.textview1135);
		dynamic_edittext7p = findViewById(R.id.dynamic_edittext7p);
		textview280 = findViewById(R.id.textview280);
		dynamic_textview7p = findViewById(R.id.dynamic_textview7p);
		textview123 = findViewById(R.id.textview123);
		dynamic_edittext8p = findViewById(R.id.dynamic_edittext8p);
		textview403 = findViewById(R.id.textview403);
		dynamic_textview8p = findViewById(R.id.dynamic_textview8p);
		textview612 = findViewById(R.id.textview612);
		dynamic_edittext9p = findViewById(R.id.dynamic_edittext9p);
		textview592 = findViewById(R.id.textview592);
		dynamic_textview9p = findViewById(R.id.dynamic_textview9p);
		textview1169 = findViewById(R.id.textview1169);
		edittext23d = findViewById(R.id.edittext23d);
		textview1170 = findViewById(R.id.textview1170);
		textview1171 = findViewById(R.id.textview1171);
		textview629 = findViewById(R.id.textview629);
		edittext22d = findViewById(R.id.edittext22d);
		textview630 = findViewById(R.id.textview630);
		textview631 = findViewById(R.id.textview631);
		textview1136 = findViewById(R.id.textview1136);
		dynamic_edittext10p = findViewById(R.id.dynamic_edittext10p);
		textview593 = findViewById(R.id.textview593);
		dynamic_textview10p = findViewById(R.id.dynamic_textview10p);
		dynamic_button1p = findViewById(R.id.dynamic_button1p);
		textview400 = findViewById(R.id.textview400);
		dynamic_edittext11p = findViewById(R.id.dynamic_edittext11p);
		textview334 = findViewById(R.id.textview334);
		textview11 = findViewById(R.id.textview11);
		textview399 = findViewById(R.id.textview399);
		dynamic_edittext12p = findViewById(R.id.dynamic_edittext12p);
		textview342 = findViewById(R.id.textview342);
		textview12 = findViewById(R.id.textview12);
		textview1139 = findViewById(R.id.textview1139);
		dynamic_edittext13p = findViewById(R.id.dynamic_edittext13p);
		textview346 = findViewById(R.id.textview346);
		textview13 = findViewById(R.id.textview13);
		textview1140 = findViewById(R.id.textview1140);
		dynamic_edittext14p = findViewById(R.id.dynamic_edittext14p);
		textview596 = findViewById(R.id.textview596);
		textview14 = findViewById(R.id.textview14);
		textview1141 = findViewById(R.id.textview1141);
		dynamic_edittext15p = findViewById(R.id.dynamic_edittext15p);
		textview357 = findViewById(R.id.textview357);
		textview15 = findViewById(R.id.textview15);
		textview1142 = findViewById(R.id.textview1142);
		dynamic_edittext16p = findViewById(R.id.dynamic_edittext16p);
		textview365 = findViewById(R.id.textview365);
		textview16 = findViewById(R.id.textview16);
		textview1147 = findViewById(R.id.textview1147);
		dynamic_edittext17p = findViewById(R.id.dynamic_edittext17p);
		textview597 = findViewById(R.id.textview597);
		textview17 = findViewById(R.id.textview17);
		textview1150 = findViewById(R.id.textview1150);
		dynamic_edittext18p = findViewById(R.id.dynamic_edittext18p);
		textview1151 = findViewById(R.id.textview1151);
		textview533 = findViewById(R.id.textview533);
		textview601 = findViewById(R.id.textview601);
		dynamic_edittext19p = findViewById(R.id.dynamic_edittext19p);
		textview602 = findViewById(R.id.textview602);
		textview603 = findViewById(R.id.textview603);
		dynamic_remove = findViewById(R.id.dynamic_remove);
		textview704 = findViewById(R.id.textview704);
		
		dynamic_button2p.setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View _view) {
				
			}
		});
	}
	
	private void initializeLogic() {
	}
	
}
