package com.my.iengineer1;

import android.animation.*;
import android.app.*;
import android.content.*;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.net.*;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.widget.*;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.DialogFragment;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import org.json.*;

public class ToipccDDewateringPriceActivity extends AppCompatActivity {
	
	private TextView textview519;
	private ScrollView vscroll1;
	private LinearLayout linear39s1;
	private LinearLayout linear713;
	private HorizontalScrollView hscroll5;
	private LinearLayout linear389;
	private TextView textview533;
	private EditText edittext94d;
	private TextView textview1d;
	private LinearLayout linear2d;
	private HorizontalScrollView hscroll4d;
	private LinearLayout linear4d;
	private HorizontalScrollView hscroll7d;
	private LinearLayout linear7d;
	private HorizontalScrollView hscroll11d;
	private LinearLayout linear11d;
	private HorizontalScrollView hscroll121d;
	private LinearLayout linear121d;
	private LinearLayout linear12d;
	private TextView textview13d;
	private LinearLayout linear13d;
	private TextView textview14d;
	private LinearLayout linear17d;
	private HorizontalScrollView hscroll18d;
	private LinearLayout linear18d;
	private TextView textview16d;
	private LinearLayout linear19d;
	private HorizontalScrollView hscroll20d;
	private LinearLayout linear20d;
	private TextView textview2021;
	private LinearLayout linear2324;
	private HorizontalScrollView hscroll4;
	private LinearLayout linear2325;
	private ImageView close;
	private LinearLayout linear720;
	private TextView textview18;
	private EditText element_nums_d;
	private TextView textview7d;
	private TextView textview16;
	private EditText element_num_d;
	private TextView textview101d;
	private LinearLayout linear100s1;
	private LinearLayout linear101s1;
	private LinearLayout linear102s1;
	private TextView textview614;
	private EditText edittext1d;
	private TextView textview124;
	private TextView textview1;
	private EditText edittext2d;
	private TextView textview1073;
	private TextView textview2d;
	private EditText edittext3d;
	private TextView textview403;
	private TextView textview3d;
	private LinearLayout linear2309;
	private LinearLayout linear2310;
	private LinearLayout linear2311;
	private TextView textview1991;
	private EditText edittext4d;
	private TextView textview1992;
	private TextView textview4;
	private EditText edittext5d;
	private TextView textview1994;
	private TextView textview5d;
	private EditText edittext6d;
	private TextView textview1996;
	private TextView textview6d;
	private LinearLayout linear2313;
	private LinearLayout linear2314;
	private LinearLayout linear2315;
	private LinearLayout linear2319;
	private TextView textview1998;
	private EditText edittext7d;
	private TextView textview1999;
	private TextView textview7;
	private EditText edittext8d;
	private TextView textview2001;
	private TextView textview8d;
	private EditText edittext9d;
	private TextView textview2003;
	private TextView textview9d;
	private EditText edittext10d;
	private TextView textview2010;
	private TextView textview10d;
	private TextView textview531;
	private EditText edittext11d;
	private TextView textview532;
	private TextView textview11d;
	private TextView textview601;
	private EditText edittext121d;
	private TextView textview602;
	private TextView textview121d;
	private Button button1d;
	private TextView textview12d;
	private LinearLayout linear391;
	private LinearLayout linear128;
	private LinearLayout linear129d;
	private LinearLayout linear155;
	private EditText edittext13d;
	private TextView textview405;
	private EditText edittext12d;
	private TextView textview4b;
	private EditText edittext15d;
	private TextView textview1803;
	private TextView textview145;
	private EditText edittext14d;
	private TextView textview5h;
	private EditText edittext129d;
	private TextView textview129;
	private TextView textview501s1;
	private EditText edittext16d;
	private TextView textview355;
	private TextView textview833;
	private EditText edittext17d;
	private TextView textview834;
	private TextView textview17d;
	private EditText edittext56d;
	private Button button2d;
	private LinearLayout linear388;
	private TextView textview815;
	private EditText edittext18d;
	private TextView textview2011;
	private EditText edittext19d;
	private TextView textview2012;
	private TextView textview19d;
	private TextView textview20d;
	private Button button3d;
	private LinearLayout linear2322;
	private TextView textview2014;
	private EditText edittext20d;
	private TextView textview22d;
	private EditText edittext21d;
	private TextView textview2016;
	private TextView textview21d;
	private EditText edittext154;
	private TextView textview334;
	private LinearLayout linear2326;
	private TextView textview2018;
	private EditText edittext22d;
	
	@Override
	protected void onCreate(Bundle _savedInstanceState) {
		super.onCreate(_savedInstanceState);
		setContentView(R.layout.toipcc_d_dewatering_price);
		initialize(_savedInstanceState);
		
		
		initializeLogic();
	}
	
	private void initialize(Bundle _savedInstanceState) {
		textview519 = findViewById(R.id.textview519);
		vscroll1 = findViewById(R.id.vscroll1);
		linear39s1 = findViewById(R.id.linear39s1);
		linear713 = findViewById(R.id.linear713);
		hscroll5 = findViewById(R.id.hscroll5);
		linear389 = findViewById(R.id.linear389);
		textview533 = findViewById(R.id.textview533);
		edittext94d = findViewById(R.id.edittext94d);
		textview1d = findViewById(R.id.textview1d);
		linear2d = findViewById(R.id.linear2d);
		hscroll4d = findViewById(R.id.hscroll4d);
		linear4d = findViewById(R.id.linear4d);
		hscroll7d = findViewById(R.id.hscroll7d);
		linear7d = findViewById(R.id.linear7d);
		hscroll11d = findViewById(R.id.hscroll11d);
		linear11d = findViewById(R.id.linear11d);
		hscroll121d = findViewById(R.id.hscroll121d);
		linear121d = findViewById(R.id.linear121d);
		linear12d = findViewById(R.id.linear12d);
		textview13d = findViewById(R.id.textview13d);
		linear13d = findViewById(R.id.linear13d);
		textview14d = findViewById(R.id.textview14d);
		linear17d = findViewById(R.id.linear17d);
		hscroll18d = findViewById(R.id.hscroll18d);
		linear18d = findViewById(R.id.linear18d);
		textview16d = findViewById(R.id.textview16d);
		linear19d = findViewById(R.id.linear19d);
		hscroll20d = findViewById(R.id.hscroll20d);
		linear20d = findViewById(R.id.linear20d);
		textview2021 = findViewById(R.id.textview2021);
		linear2324 = findViewById(R.id.linear2324);
		hscroll4 = findViewById(R.id.hscroll4);
		linear2325 = findViewById(R.id.linear2325);
		close = findViewById(R.id.close);
		linear720 = findViewById(R.id.linear720);
		textview18 = findViewById(R.id.textview18);
		element_nums_d = findViewById(R.id.element_nums_d);
		textview7d = findViewById(R.id.textview7d);
		textview16 = findViewById(R.id.textview16);
		element_num_d = findViewById(R.id.element_num_d);
		textview101d = findViewById(R.id.textview101d);
		linear100s1 = findViewById(R.id.linear100s1);
		linear101s1 = findViewById(R.id.linear101s1);
		linear102s1 = findViewById(R.id.linear102s1);
		textview614 = findViewById(R.id.textview614);
		edittext1d = findViewById(R.id.edittext1d);
		textview124 = findViewById(R.id.textview124);
		textview1 = findViewById(R.id.textview1);
		edittext2d = findViewById(R.id.edittext2d);
		textview1073 = findViewById(R.id.textview1073);
		textview2d = findViewById(R.id.textview2d);
		edittext3d = findViewById(R.id.edittext3d);
		textview403 = findViewById(R.id.textview403);
		textview3d = findViewById(R.id.textview3d);
		linear2309 = findViewById(R.id.linear2309);
		linear2310 = findViewById(R.id.linear2310);
		linear2311 = findViewById(R.id.linear2311);
		textview1991 = findViewById(R.id.textview1991);
		edittext4d = findViewById(R.id.edittext4d);
		textview1992 = findViewById(R.id.textview1992);
		textview4 = findViewById(R.id.textview4);
		edittext5d = findViewById(R.id.edittext5d);
		textview1994 = findViewById(R.id.textview1994);
		textview5d = findViewById(R.id.textview5d);
		edittext6d = findViewById(R.id.edittext6d);
		textview1996 = findViewById(R.id.textview1996);
		textview6d = findViewById(R.id.textview6d);
		linear2313 = findViewById(R.id.linear2313);
		linear2314 = findViewById(R.id.linear2314);
		linear2315 = findViewById(R.id.linear2315);
		linear2319 = findViewById(R.id.linear2319);
		textview1998 = findViewById(R.id.textview1998);
		edittext7d = findViewById(R.id.edittext7d);
		textview1999 = findViewById(R.id.textview1999);
		textview7 = findViewById(R.id.textview7);
		edittext8d = findViewById(R.id.edittext8d);
		textview2001 = findViewById(R.id.textview2001);
		textview8d = findViewById(R.id.textview8d);
		edittext9d = findViewById(R.id.edittext9d);
		textview2003 = findViewById(R.id.textview2003);
		textview9d = findViewById(R.id.textview9d);
		edittext10d = findViewById(R.id.edittext10d);
		textview2010 = findViewById(R.id.textview2010);
		textview10d = findViewById(R.id.textview10d);
		textview531 = findViewById(R.id.textview531);
		edittext11d = findViewById(R.id.edittext11d);
		textview532 = findViewById(R.id.textview532);
		textview11d = findViewById(R.id.textview11d);
		textview601 = findViewById(R.id.textview601);
		edittext121d = findViewById(R.id.edittext121d);
		textview602 = findViewById(R.id.textview602);
		textview121d = findViewById(R.id.textview121d);
		button1d = findViewById(R.id.button1d);
		textview12d = findViewById(R.id.textview12d);
		linear391 = findViewById(R.id.linear391);
		linear128 = findViewById(R.id.linear128);
		linear129d = findViewById(R.id.linear129d);
		linear155 = findViewById(R.id.linear155);
		edittext13d = findViewById(R.id.edittext13d);
		textview405 = findViewById(R.id.textview405);
		edittext12d = findViewById(R.id.edittext12d);
		textview4b = findViewById(R.id.textview4b);
		edittext15d = findViewById(R.id.edittext15d);
		textview1803 = findViewById(R.id.textview1803);
		textview145 = findViewById(R.id.textview145);
		edittext14d = findViewById(R.id.edittext14d);
		textview5h = findViewById(R.id.textview5h);
		edittext129d = findViewById(R.id.edittext129d);
		textview129 = findViewById(R.id.textview129);
		textview501s1 = findViewById(R.id.textview501s1);
		edittext16d = findViewById(R.id.edittext16d);
		textview355 = findViewById(R.id.textview355);
		textview833 = findViewById(R.id.textview833);
		edittext17d = findViewById(R.id.edittext17d);
		textview834 = findViewById(R.id.textview834);
		textview17d = findViewById(R.id.textview17d);
		edittext56d = findViewById(R.id.edittext56d);
		button2d = findViewById(R.id.button2d);
		linear388 = findViewById(R.id.linear388);
		textview815 = findViewById(R.id.textview815);
		edittext18d = findViewById(R.id.edittext18d);
		textview2011 = findViewById(R.id.textview2011);
		edittext19d = findViewById(R.id.edittext19d);
		textview2012 = findViewById(R.id.textview2012);
		textview19d = findViewById(R.id.textview19d);
		textview20d = findViewById(R.id.textview20d);
		button3d = findViewById(R.id.button3d);
		linear2322 = findViewById(R.id.linear2322);
		textview2014 = findViewById(R.id.textview2014);
		edittext20d = findViewById(R.id.edittext20d);
		textview22d = findViewById(R.id.textview22d);
		edittext21d = findViewById(R.id.edittext21d);
		textview2016 = findViewById(R.id.textview2016);
		textview21d = findViewById(R.id.textview21d);
		edittext154 = findViewById(R.id.edittext154);
		textview334 = findViewById(R.id.textview334);
		linear2326 = findViewById(R.id.linear2326);
		textview2018 = findViewById(R.id.textview2018);
		edittext22d = findViewById(R.id.edittext22d);
	}
	
	private void initializeLogic() {
	}
	

	@Override
	public boolean onCreateOptionsMenu(Menu menu) {
		getMenuInflater().inflate(R.menu.menu_calc, menu);
		return true;
	}

	@Override
	public boolean onOptionsItemSelected(MenuItem item) {
		int id = item.getItemId();
		if (id == R.id.action_help) {
			new androidx.appcompat.app.AlertDialog.Builder(this)
				.setTitle("طريقة الاستخدام")
				.setMessage("أدخل القيم في الحقول المُدخلة (ذات الخلفية الخضراء) ثم اضغط على زر الحساب للحصول على النتائج.")
				.setPositiveButton("حسناً", null)
				.show();
			return true;
		} else if (id == R.id.action_print) {
			_PrintHelper(linear1);
			return true;
		}
		return super.onOptionsItemSelected(item);
	}


}
