package com.my.iengineer1;

import android.animation.*;
import android.app.*;
import android.content.*;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.net.*;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.widget.*;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.DialogFragment;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import org.json.*;

public class ToipDDrainagePipeLineSlopeActivity extends AppCompatActivity {
	
	private TextView textview519;
	private ScrollView vscroll1;
	private LinearLayout linear205;
	private LinearLayout linear713;
	private LinearLayout linear728;
	private LinearLayout linear195;
	private LinearLayout linear201;
	private LinearLayout linear2;
	private LinearLayout linear203;
	private LinearLayout linear3;
	private TextView textview18d;
	private LinearLayout linear723;
	private TextView textview19d;
	private LinearLayout linear43;
	private HorizontalScrollView hscroll8;
	private TextView textview20d;
	private TextView textview21d;
	private LinearLayout linear198;
	private LinearLayout linear724;
	private LinearLayout linear726;
	private LinearLayout linear727;
	private LinearLayout linear200;
	private ImageView close;
	private LinearLayout linear720;
	private EditText edittext1d;
	private TextView textview1d;
	private TextView textview14;
	private EditText edittext2d;
	private TextView textview607;
	private TextView textview2d;
	private TextView textview611;
	private EditText edittext3d;
	private TextView textview609;
	private TextView textview3d;
	private LinearLayout linear127;
	private LinearLayout linear125;
	private EditText edittext4d;
	private TextView textview4d;
	private EditText edittext5d;
	private TextView textview601;
	private TextView textview5d;
	private LinearLayout linear126;
	private LinearLayout linear157;
	private EditText edittext6d;
	private TextView textview6d;
	private EditText edittext7d;
	private TextView textview405;
	private TextView textview7d;
	private Button button3d;
	private TextView textview614;
	private Button button2d;
	private TextView textview612;
	private Button button1d;
	private Button button6d;
	private TextView textview812;
	private Button button5d;
	private TextView textview813;
	private Button button4d;
	private Button button9d;
	private TextView textview816;
	private Button button8d;
	private TextView textview817;
	private Button button7d;
	private Button button11d;
	private TextView textview819;
	private Button button10d;
	private LinearLayout linear199;
	private TextView textview22d;
	private TextView textview531;
	private EditText edittext8d;
	private TextView textview532;
	private TextView textview8d;
	
	@Override
	protected void onCreate(Bundle _savedInstanceState) {
		super.onCreate(_savedInstanceState);
		setContentView(R.layout.toip_d_drainage_pipe_line_slope);
		initialize(_savedInstanceState);
		
		
		initializeLogic();
	}
	
	private void initialize(Bundle _savedInstanceState) {
		textview519 = findViewById(R.id.textview519);
		vscroll1 = findViewById(R.id.vscroll1);
		linear205 = findViewById(R.id.linear205);
		linear713 = findViewById(R.id.linear713);
		linear728 = findViewById(R.id.linear728);
		linear195 = findViewById(R.id.linear195);
		linear201 = findViewById(R.id.linear201);
		linear2 = findViewById(R.id.linear2);
		linear203 = findViewById(R.id.linear203);
		linear3 = findViewById(R.id.linear3);
		textview18d = findViewById(R.id.textview18d);
		linear723 = findViewById(R.id.linear723);
		textview19d = findViewById(R.id.textview19d);
		linear43 = findViewById(R.id.linear43);
		hscroll8 = findViewById(R.id.hscroll8);
		textview20d = findViewById(R.id.textview20d);
		textview21d = findViewById(R.id.textview21d);
		linear198 = findViewById(R.id.linear198);
		linear724 = findViewById(R.id.linear724);
		linear726 = findViewById(R.id.linear726);
		linear727 = findViewById(R.id.linear727);
		linear200 = findViewById(R.id.linear200);
		close = findViewById(R.id.close);
		linear720 = findViewById(R.id.linear720);
		edittext1d = findViewById(R.id.edittext1d);
		textview1d = findViewById(R.id.textview1d);
		textview14 = findViewById(R.id.textview14);
		edittext2d = findViewById(R.id.edittext2d);
		textview607 = findViewById(R.id.textview607);
		textview2d = findViewById(R.id.textview2d);
		textview611 = findViewById(R.id.textview611);
		edittext3d = findViewById(R.id.edittext3d);
		textview609 = findViewById(R.id.textview609);
		textview3d = findViewById(R.id.textview3d);
		linear127 = findViewById(R.id.linear127);
		linear125 = findViewById(R.id.linear125);
		edittext4d = findViewById(R.id.edittext4d);
		textview4d = findViewById(R.id.textview4d);
		edittext5d = findViewById(R.id.edittext5d);
		textview601 = findViewById(R.id.textview601);
		textview5d = findViewById(R.id.textview5d);
		linear126 = findViewById(R.id.linear126);
		linear157 = findViewById(R.id.linear157);
		edittext6d = findViewById(R.id.edittext6d);
		textview6d = findViewById(R.id.textview6d);
		edittext7d = findViewById(R.id.edittext7d);
		textview405 = findViewById(R.id.textview405);
		textview7d = findViewById(R.id.textview7d);
		button3d = findViewById(R.id.button3d);
		textview614 = findViewById(R.id.textview614);
		button2d = findViewById(R.id.button2d);
		textview612 = findViewById(R.id.textview612);
		button1d = findViewById(R.id.button1d);
		button6d = findViewById(R.id.button6d);
		textview812 = findViewById(R.id.textview812);
		button5d = findViewById(R.id.button5d);
		textview813 = findViewById(R.id.textview813);
		button4d = findViewById(R.id.button4d);
		button9d = findViewById(R.id.button9d);
		textview816 = findViewById(R.id.textview816);
		button8d = findViewById(R.id.button8d);
		textview817 = findViewById(R.id.textview817);
		button7d = findViewById(R.id.button7d);
		button11d = findViewById(R.id.button11d);
		textview819 = findViewById(R.id.textview819);
		button10d = findViewById(R.id.button10d);
		linear199 = findViewById(R.id.linear199);
		textview22d = findViewById(R.id.textview22d);
		textview531 = findViewById(R.id.textview531);
		edittext8d = findViewById(R.id.edittext8d);
		textview532 = findViewById(R.id.textview532);
		textview8d = findViewById(R.id.textview8d);
	}
	
	private void initializeLogic() {
	}
	
}
