package com.my.iengineer1;

import android.animation.*;
import android.app.*;
import android.content.*;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.net.*;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.widget.*;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.DialogFragment;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import org.json.*;

public class ToipqcSoilWorksActivity extends AppCompatActivity {
	
	private TextView textview519;
	private ScrollView vscroll1;
	private LinearLayout linear205;
	private LinearLayout linear713;
	private HorizontalScrollView hscroll13;
	private LinearLayout linear389d;
	private HorizontalScrollView hscroll16;
	private LinearLayout linear195;
	private HorizontalScrollView hscroll11;
	private LinearLayout linear127;
	private LinearLayout linear202;
	private LinearLayout linear120d;
	private LinearLayout linear201d;
	private LinearLayout linear613d;
	private LinearLayout linear19d;
	private HorizontalScrollView hscroll8d;
	private HorizontalScrollView hscroll81d;
	private LinearLayout linear8d;
	private HorizontalScrollView hscroll82d;
	private LinearLayout linear126d;
	private HorizontalScrollView hscroll10;
	private LinearLayout linear20d;
	private LinearLayout linear21d;
	private LinearLayout linear22d;
	private TextView textview341d;
	private LinearLayout linear125d;
	private LinearLayout linear254;
	private LinearLayout linear301d;
	private TextView textview54d;
	private HorizontalScrollView hscroll301d;
	private LinearLayout linear9d;
	private TextView textview55d;
	private HorizontalScrollView hscroll83d;
	private LinearLayout linear23d;
	private HorizontalScrollView hscroll9d;
	private LinearLayout linear157;
	private LinearLayout linear119d;
	private LinearLayout linear199;
	private LinearLayout linear43d;
	private LinearLayout linear74;
	private ImageView close;
	private LinearLayout linear720;
	private TextView textview180;
	private TextView textview2d;
	private EditText element_nums_d;
	private TextView textview3d;
	private TextView textview160;
	private EditText element_num_d;
	private TextView textview1d;
	private EditText edittext1d;
	private TextView textview603;
	private TextView textview604d;
	private EditText edittext3d;
	private TextView textview354;
	private TextView textview1421;
	private EditText edittext15d;
	private TextView textview1422;
	private TextView textview1423d;
	private TextView textview614d;
	private EditText edittext2d;
	private TextView textview612;
	private TextView textview613d;
	private LinearLayout linear40;
	private LinearLayout linear808;
	private TextView textview122;
	private LinearLayout linear77;
	private TextView textview1520;
	private LinearLayout linear809;
	private LinearLayout linear810;
	private LinearLayout linear811;
	private LinearLayout linear812;
	private EditText edittext190d;
	private TextView textview1521;
	private EditText edittext191d;
	private TextView textview1522;
	private TextView textview1523;
	private EditText edittext192d;
	private TextView textview1524;
	private TextView textview1525;
	private TextView textview1526;
	private EditText edittext193d;
	private TextView textview1527;
	private TextView textview1528;
	private TextView textview123;
	private LinearLayout linear813;
	private LinearLayout linear814;
	private LinearLayout linear815;
	private LinearLayout linear816;
	private EditText edittext194d;
	private TextView textview1529;
	private EditText edittext195d;
	private TextView textview1530;
	private TextView textview1531;
	private EditText edittext196d;
	private TextView textview340;
	private TextView textview138;
	private TextView textview1532;
	private EditText edittext197d;
	private TextView textview1533;
	private TextView textview1534;
	private TextView textview1535;
	private EditText edittext198d;
	private TextView textview1536;
	private TextView textview1537;
	private TextView textview58d;
	private EditText edittext6d;
	private TextView textview353;
	private TextView textview57d;
	private TextView textview60d;
	private EditText edittext4d;
	private TextView textview607;
	private TextView textview59d;
	private TextView textview64d;
	private EditText edittext5d;
	private TextView textview609;
	private TextView textview63d;
	private LinearLayout linear721;
	private LinearLayout linear723;
	private LinearLayout linear722;
	private TextView textview135;
	private EditText edittext8d;
	private TextView textview601;
	private TextView textview592;
	private TextView textview136;
	private EditText edittext7d;
	private Button button2d;
	private TextView textview2371;
	private EditText edittext301d;
	private TextView textview2372;
	private TextView textview301d;
	private TextView textview62d;
	private EditText edittext199d;
	private TextView textview1539;
	private TextView textview61d;
	private TextView textview511d;
	private EditText edittext9d;
	private TextView textview334;
	private TextView textview111d;
	private TextView textview512d;
	private EditText edittext10d;
	private TextView textview405;
	private TextView textview112d;
	private TextView textview513d;
	private EditText edittext11d;
	private TextView textview532;
	private TextView textview113d;
	private TextView textview514d;
	private EditText edittext12d;
	private TextView textview286;
	private TextView textview114d;
	
	@Override
	protected void onCreate(Bundle _savedInstanceState) {
		super.onCreate(_savedInstanceState);
		setContentView(R.layout.toipqc_soil_works);
		initialize(_savedInstanceState);
		
		
		initializeLogic();
	}
	
	private void initialize(Bundle _savedInstanceState) {
		textview519 = findViewById(R.id.textview519);
		vscroll1 = findViewById(R.id.vscroll1);
		linear205 = findViewById(R.id.linear205);
		linear713 = findViewById(R.id.linear713);
		hscroll13 = findViewById(R.id.hscroll13);
		linear389d = findViewById(R.id.linear389d);
		hscroll16 = findViewById(R.id.hscroll16);
		linear195 = findViewById(R.id.linear195);
		hscroll11 = findViewById(R.id.hscroll11);
		linear127 = findViewById(R.id.linear127);
		linear202 = findViewById(R.id.linear202);
		linear120d = findViewById(R.id.linear120d);
		linear201d = findViewById(R.id.linear201d);
		linear613d = findViewById(R.id.linear613d);
		linear19d = findViewById(R.id.linear19d);
		hscroll8d = findViewById(R.id.hscroll8d);
		hscroll81d = findViewById(R.id.hscroll81d);
		linear8d = findViewById(R.id.linear8d);
		hscroll82d = findViewById(R.id.hscroll82d);
		linear126d = findViewById(R.id.linear126d);
		hscroll10 = findViewById(R.id.hscroll10);
		linear20d = findViewById(R.id.linear20d);
		linear21d = findViewById(R.id.linear21d);
		linear22d = findViewById(R.id.linear22d);
		textview341d = findViewById(R.id.textview341d);
		linear125d = findViewById(R.id.linear125d);
		linear254 = findViewById(R.id.linear254);
		linear301d = findViewById(R.id.linear301d);
		textview54d = findViewById(R.id.textview54d);
		hscroll301d = findViewById(R.id.hscroll301d);
		linear9d = findViewById(R.id.linear9d);
		textview55d = findViewById(R.id.textview55d);
		hscroll83d = findViewById(R.id.hscroll83d);
		linear23d = findViewById(R.id.linear23d);
		hscroll9d = findViewById(R.id.hscroll9d);
		linear157 = findViewById(R.id.linear157);
		linear119d = findViewById(R.id.linear119d);
		linear199 = findViewById(R.id.linear199);
		linear43d = findViewById(R.id.linear43d);
		linear74 = findViewById(R.id.linear74);
		close = findViewById(R.id.close);
		linear720 = findViewById(R.id.linear720);
		textview180 = findViewById(R.id.textview180);
		textview2d = findViewById(R.id.textview2d);
		element_nums_d = findViewById(R.id.element_nums_d);
		textview3d = findViewById(R.id.textview3d);
		textview160 = findViewById(R.id.textview160);
		element_num_d = findViewById(R.id.element_num_d);
		textview1d = findViewById(R.id.textview1d);
		edittext1d = findViewById(R.id.edittext1d);
		textview603 = findViewById(R.id.textview603);
		textview604d = findViewById(R.id.textview604d);
		edittext3d = findViewById(R.id.edittext3d);
		textview354 = findViewById(R.id.textview354);
		textview1421 = findViewById(R.id.textview1421);
		edittext15d = findViewById(R.id.edittext15d);
		textview1422 = findViewById(R.id.textview1422);
		textview1423d = findViewById(R.id.textview1423d);
		textview614d = findViewById(R.id.textview614d);
		edittext2d = findViewById(R.id.edittext2d);
		textview612 = findViewById(R.id.textview612);
		textview613d = findViewById(R.id.textview613d);
		linear40 = findViewById(R.id.linear40);
		linear808 = findViewById(R.id.linear808);
		textview122 = findViewById(R.id.textview122);
		linear77 = findViewById(R.id.linear77);
		textview1520 = findViewById(R.id.textview1520);
		linear809 = findViewById(R.id.linear809);
		linear810 = findViewById(R.id.linear810);
		linear811 = findViewById(R.id.linear811);
		linear812 = findViewById(R.id.linear812);
		edittext190d = findViewById(R.id.edittext190d);
		textview1521 = findViewById(R.id.textview1521);
		edittext191d = findViewById(R.id.edittext191d);
		textview1522 = findViewById(R.id.textview1522);
		textview1523 = findViewById(R.id.textview1523);
		edittext192d = findViewById(R.id.edittext192d);
		textview1524 = findViewById(R.id.textview1524);
		textview1525 = findViewById(R.id.textview1525);
		textview1526 = findViewById(R.id.textview1526);
		edittext193d = findViewById(R.id.edittext193d);
		textview1527 = findViewById(R.id.textview1527);
		textview1528 = findViewById(R.id.textview1528);
		textview123 = findViewById(R.id.textview123);
		linear813 = findViewById(R.id.linear813);
		linear814 = findViewById(R.id.linear814);
		linear815 = findViewById(R.id.linear815);
		linear816 = findViewById(R.id.linear816);
		edittext194d = findViewById(R.id.edittext194d);
		textview1529 = findViewById(R.id.textview1529);
		edittext195d = findViewById(R.id.edittext195d);
		textview1530 = findViewById(R.id.textview1530);
		textview1531 = findViewById(R.id.textview1531);
		edittext196d = findViewById(R.id.edittext196d);
		textview340 = findViewById(R.id.textview340);
		textview138 = findViewById(R.id.textview138);
		textview1532 = findViewById(R.id.textview1532);
		edittext197d = findViewById(R.id.edittext197d);
		textview1533 = findViewById(R.id.textview1533);
		textview1534 = findViewById(R.id.textview1534);
		textview1535 = findViewById(R.id.textview1535);
		edittext198d = findViewById(R.id.edittext198d);
		textview1536 = findViewById(R.id.textview1536);
		textview1537 = findViewById(R.id.textview1537);
		textview58d = findViewById(R.id.textview58d);
		edittext6d = findViewById(R.id.edittext6d);
		textview353 = findViewById(R.id.textview353);
		textview57d = findViewById(R.id.textview57d);
		textview60d = findViewById(R.id.textview60d);
		edittext4d = findViewById(R.id.edittext4d);
		textview607 = findViewById(R.id.textview607);
		textview59d = findViewById(R.id.textview59d);
		textview64d = findViewById(R.id.textview64d);
		edittext5d = findViewById(R.id.edittext5d);
		textview609 = findViewById(R.id.textview609);
		textview63d = findViewById(R.id.textview63d);
		linear721 = findViewById(R.id.linear721);
		linear723 = findViewById(R.id.linear723);
		linear722 = findViewById(R.id.linear722);
		textview135 = findViewById(R.id.textview135);
		edittext8d = findViewById(R.id.edittext8d);
		textview601 = findViewById(R.id.textview601);
		textview592 = findViewById(R.id.textview592);
		textview136 = findViewById(R.id.textview136);
		edittext7d = findViewById(R.id.edittext7d);
		button2d = findViewById(R.id.button2d);
		textview2371 = findViewById(R.id.textview2371);
		edittext301d = findViewById(R.id.edittext301d);
		textview2372 = findViewById(R.id.textview2372);
		textview301d = findViewById(R.id.textview301d);
		textview62d = findViewById(R.id.textview62d);
		edittext199d = findViewById(R.id.edittext199d);
		textview1539 = findViewById(R.id.textview1539);
		textview61d = findViewById(R.id.textview61d);
		textview511d = findViewById(R.id.textview511d);
		edittext9d = findViewById(R.id.edittext9d);
		textview334 = findViewById(R.id.textview334);
		textview111d = findViewById(R.id.textview111d);
		textview512d = findViewById(R.id.textview512d);
		edittext10d = findViewById(R.id.edittext10d);
		textview405 = findViewById(R.id.textview405);
		textview112d = findViewById(R.id.textview112d);
		textview513d = findViewById(R.id.textview513d);
		edittext11d = findViewById(R.id.edittext11d);
		textview532 = findViewById(R.id.textview532);
		textview113d = findViewById(R.id.textview113d);
		textview514d = findViewById(R.id.textview514d);
		edittext12d = findViewById(R.id.edittext12d);
		textview286 = findViewById(R.id.textview286);
		textview114d = findViewById(R.id.textview114d);
	}
	
	private void initializeLogic() {
	}
	
}
