package com.my.iengineer1;

import android.animation.*;
import android.app.*;
import android.content.*;
import android.content.res.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.media.*;
import android.net.*;
import android.os.*;
import android.text.*;
import android.text.style.*;
import android.util.*;
import android.view.*;
import android.view.View.*;
import android.view.animation.*;
import android.webkit.*;
import android.widget.*;
import android.widget.Button;
import android.widget.EditText;
import android.widget.HorizontalScrollView;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.fragment.app.DialogFragment;
import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import java.io.*;
import java.text.*;
import java.util.*;
import java.util.regex.*;
import org.json.*;

public class ToipDSewageVilocityChecksActivity extends AppCompatActivity {
	
	private TextView textview519;
	private ScrollView vscroll1;
	private LinearLayout linear39s1;
	private LinearLayout linear713;
	private HorizontalScrollView hscroll3;
	private LinearLayout linear389;
	private HorizontalScrollView hscroll2;
	private Button button1d;
	private LinearLayout linear11d;
	private LinearLayout linear10d;
	private TextView textview612;
	private Button button2d;
	private LinearLayout linear23d;
	private LinearLayout linear2d;
	private LinearLayout linear3d;
	private LinearLayout linear4d;
	private LinearLayout linear5d;
	private HorizontalScrollView hscroll8s1;
	private Button button3d;
	private HorizontalScrollView hscroll1;
	private LinearLayout linear6d;
	private TextView textview1650;
	private LinearLayout linear7;
	private ImageView close;
	private LinearLayout linear720;
	private TextView textview18;
	private EditText element_numsd;
	private TextView textview17;
	private TextView textview16;
	private EditText element_numd;
	private TextView textview101;
	private LinearLayout linear2334;
	private LinearLayout linear2332;
	private Button button8d;
	private Button button9d;
	private Button button10d;
	private Button button4d;
	private Button button5d;
	private Button button6d;
	private Button button7d;
	private EditText edittext1d;
	private TextView textview124;
	private TextView textview1;
	private Button button12d;
	private Button button11d;
	private TextView textview1991;
	private EditText edittext2d;
	private TextView textview1992;
	private TextView textview2;
	private TextView textview65;
	private EditText edittext3d;
	private TextView textview1073;
	private TextView textview4;
	private TextView textview2010;
	private EditText edittext4d;
	private TextView textview403;
	private TextView textview5;
	private TextView textview1996;
	private EditText edittext5d;
	private TextView textview1994;
	private TextView textview6;
	private TextView textview1998;
	private EditText edittext6d;
	private TextView textview1999;
	private TextView textview3;
	private TextView textview12;
	private LinearLayout linear155;
	private TextView textview7d;
	private TextView textview501s1;
	private EditText edittext7d;
	private TextView textview355;
	
	@Override
	protected void onCreate(Bundle _savedInstanceState) {
		super.onCreate(_savedInstanceState);
		setContentView(R.layout.toip_d_sewage_vilocity_checks);
		initialize(_savedInstanceState);
		
		
		initializeLogic();
	}
	
	private void initialize(Bundle _savedInstanceState) {
		textview519 = findViewById(R.id.textview519);
		vscroll1 = findViewById(R.id.vscroll1);
		linear39s1 = findViewById(R.id.linear39s1);
		linear713 = findViewById(R.id.linear713);
		hscroll3 = findViewById(R.id.hscroll3);
		linear389 = findViewById(R.id.linear389);
		hscroll2 = findViewById(R.id.hscroll2);
		button1d = findViewById(R.id.button1d);
		linear11d = findViewById(R.id.linear11d);
		linear10d = findViewById(R.id.linear10d);
		textview612 = findViewById(R.id.textview612);
		button2d = findViewById(R.id.button2d);
		linear23d = findViewById(R.id.linear23d);
		linear2d = findViewById(R.id.linear2d);
		linear3d = findViewById(R.id.linear3d);
		linear4d = findViewById(R.id.linear4d);
		linear5d = findViewById(R.id.linear5d);
		hscroll8s1 = findViewById(R.id.hscroll8s1);
		button3d = findViewById(R.id.button3d);
		hscroll1 = findViewById(R.id.hscroll1);
		linear6d = findViewById(R.id.linear6d);
		textview1650 = findViewById(R.id.textview1650);
		linear7 = findViewById(R.id.linear7);
		close = findViewById(R.id.close);
		linear720 = findViewById(R.id.linear720);
		textview18 = findViewById(R.id.textview18);
		element_numsd = findViewById(R.id.element_numsd);
		textview17 = findViewById(R.id.textview17);
		textview16 = findViewById(R.id.textview16);
		element_numd = findViewById(R.id.element_numd);
		textview101 = findViewById(R.id.textview101);
		linear2334 = findViewById(R.id.linear2334);
		linear2332 = findViewById(R.id.linear2332);
		button8d = findViewById(R.id.button8d);
		button9d = findViewById(R.id.button9d);
		button10d = findViewById(R.id.button10d);
		button4d = findViewById(R.id.button4d);
		button5d = findViewById(R.id.button5d);
		button6d = findViewById(R.id.button6d);
		button7d = findViewById(R.id.button7d);
		edittext1d = findViewById(R.id.edittext1d);
		textview124 = findViewById(R.id.textview124);
		textview1 = findViewById(R.id.textview1);
		button12d = findViewById(R.id.button12d);
		button11d = findViewById(R.id.button11d);
		textview1991 = findViewById(R.id.textview1991);
		edittext2d = findViewById(R.id.edittext2d);
		textview1992 = findViewById(R.id.textview1992);
		textview2 = findViewById(R.id.textview2);
		textview65 = findViewById(R.id.textview65);
		edittext3d = findViewById(R.id.edittext3d);
		textview1073 = findViewById(R.id.textview1073);
		textview4 = findViewById(R.id.textview4);
		textview2010 = findViewById(R.id.textview2010);
		edittext4d = findViewById(R.id.edittext4d);
		textview403 = findViewById(R.id.textview403);
		textview5 = findViewById(R.id.textview5);
		textview1996 = findViewById(R.id.textview1996);
		edittext5d = findViewById(R.id.edittext5d);
		textview1994 = findViewById(R.id.textview1994);
		textview6 = findViewById(R.id.textview6);
		textview1998 = findViewById(R.id.textview1998);
		edittext6d = findViewById(R.id.edittext6d);
		textview1999 = findViewById(R.id.textview1999);
		textview3 = findViewById(R.id.textview3);
		textview12 = findViewById(R.id.textview12);
		linear155 = findViewById(R.id.linear155);
		textview7d = findViewById(R.id.textview7d);
		textview501s1 = findViewById(R.id.textview501s1);
		edittext7d = findViewById(R.id.edittext7d);
		textview355 = findViewById(R.id.textview355);
	}
	
	private void initializeLogic() {
	}
	
}
